#!/usr/bin/env bash
# OCaml executable linker wrapper - expands CONDA_OCAML_MKEXE environment variable
# CONDA_OCAML_MKEXE may include flags (e.g., "cc -Wl,-E")
# Automatically adds -L${CONDA_PREFIX}/lib for runtime library search (relocatable)
# shellcheck disable=SC2086

# Determine base command: use CONDA_OCAML_MKEXE if set, otherwise platform-aware default
if [[ -n "${CONDA_OCAML_MKEXE:-}" ]]; then
  MKEXE_CMD="${CONDA_OCAML_MKEXE}"
elif [[ "$OSTYPE" == darwin* ]]; then
  # macOS needs rpath for downstream binaries to find libzstd
  MKEXE_CMD="cc -Wl,-rpath,@executable_path/../lib"
else
  MKEXE_CMD="cc"
fi

# Add -L for library search path if CONDA_PREFIX is set
if [[ -n "${CONDA_PREFIX:-}" ]]; then
  exec ${MKEXE_CMD} -L"${CONDA_PREFIX}/lib" "$@"
else
  exec ${MKEXE_CMD} "$@"
fi
