#!/usr/bin/env bash
# OCaml shared library linker wrapper - expands CONDA_OCAML_MKDLL environment variable
# CONDA_OCAML_MKDLL may include flags (e.g., "cc -shared -undefined dynamic_lookup")
. "$(dirname "$0")/conda-ocaml-common"

MKDLL_TOOL="$(ocaml_darwin_fallback "${CONDA_OCAML_MKDLL:-}" "cc -shared -undefined dynamic_lookup" "cc -shared")"
# shellcheck disable=SC2086
exec ${MKDLL_TOOL} "$@"
