#!/usr/bin/env bash
# OCaml shared library linker wrapper - expands CONDA_OCAML_MKDLL environment variable
# CONDA_OCAML_MKDLL may include flags (e.g., "cc -shared -undefined dynamic_lookup")
# shellcheck disable=SC2086
if [[ -z "${CONDA_OCAML_MKDLL:-}" ]] && [[ "$OSTYPE" == darwin* ]]; then
  exec cc -shared -undefined dynamic_lookup "$@"
else
  exec ${CONDA_OCAML_MKDLL:-cc -shared} "$@"
fi
