unset OCAMLLIB
unset OCAML_PREFIX
unset CONDA_OCAML_AS
unset CONDA_OCAML_CC
unset CONDA_OCAML_AR
unset CONDA_OCAML_MKDLL
unset CONDA_OCAML_MKEXE

if [[ -n "${_OCAML_OCAMLLIB_CONDA_BACKUP:-}" ]]; then
    export OCAMLLIB="${_OCAML_OCAMLLIB_CONDA_BACKUP}"
    unset _OCAML_OCAMLLIB_CONDA_BACKUP
fi
if [[ -n "${_OCAML_OCAML_PREFIX_CONDA_BACKUP:-}" ]]; then
    export OCAML_PREFIX="${_OCAML_OCAML_PREFIX_CONDA_BACKUP}"
    unset _OCAML_OCAML_PREFIX_CONDA_BACKUP
fi

# macOS: Restore DYLD_FALLBACK_LIBRARY_PATH
if [[ -n "${_OCAML_DYLD_FALLBACK_LIBRARY_PATH_BACKUP+x}" ]]; then
    if [[ -n "${_OCAML_DYLD_FALLBACK_LIBRARY_PATH_BACKUP}" ]]; then
        export DYLD_FALLBACK_LIBRARY_PATH="${_OCAML_DYLD_FALLBACK_LIBRARY_PATH_BACKUP}"
    else
        unset DYLD_FALLBACK_LIBRARY_PATH
    fi
    unset _OCAML_DYLD_FALLBACK_LIBRARY_PATH_BACKUP
fi
