unset OCAMLLIB
unset OCAML_PREFIX
unset CONDA_OCAML_AS
unset CONDA_OCAML_CC
unset CONDA_OCAML_AR
unset CONDA_OCAML_MKDLL
unset CONDA_OCAML_MKEXE

if [[ -n "${_OCAML_OCAMLLIB_CONDA_BACKUP:-}" ]]; then
    export OCAMLLIB="${_OCAML_OCAMLLIB_CONDA_BACKUP}"
    unset _OCAML_OCAMLLIB_CONDA_BACKUP
fi
if [[ -n "${_OCAML_OCAML_PREFIX_CONDA_BACKUP:-}" ]]; then
    export OCAML_PREFIX="${_OCAML_OCAML_PREFIX_CONDA_BACKUP}"
    unset _OCAML_OCAML_PREFIX_CONDA_BACKUP
fi
