unset OCAMLLIB
unset OCAML_PREFIX
if [[ -n "$_OCAML_OCAMLLIB_CONDA_BACKUP" ]]; then
    export OCAMLLIB=$_OCAML_OCAMLLIB_CONDA_BACKUP
    unset _OCAML_OCAMLLIB_CONDA_BACKUP
fi
if [[ -n "$_OCAML_OCAML_PREFIX_CONDA_BACKUP" ]]; then
    export OCAMLLIB=$_OCAML_OCAML_PREFIX_CONDA_BACKUP
    unset _OCAML_OCAML_PREFIX_CONDA_BACKUP
fi
