#!/usr/bin/env bash
# OCaml executable linker wrapper - expands CONDA_OCAML_MKEXE environment variable
# CONDA_OCAML_MKEXE may include flags (e.g., "cc -Wl,-E")
# shellcheck disable=SC2086
exec ${CONDA_OCAML_MKEXE:-cc} "$@"
