{% set name = "ocaml" %}
{% set version = "5.3.0" %}
{% set version_major = version.split(".")[0] %}
{% set version_minor = version.split(".")[1] %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://caml.inria.fr/pub/distrib/{{ name }}-{{ version_major }}.{{ version_minor }}/{{ name }}-{{ version }}.tar.gz
  sha256: 22c1dd9de21bf43b62d1909041fb5fad648905227bf69550a6a6bef31e654f38
  patches:
    - prefix_fix.diff

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage("ocaml", max_pin="x.x.x") }}
  detect_binary_files_with_prefix: false

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - make
  host:
  run:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}

test:
  commands:
    - ocaml -version | grep {{ version }}
    - ocamlc -version| grep {{ version }}
    - ocamlcmt -help | grep FILE
    - ocamlcp -version | grep {{ version }}
    - ocamldoc -version | grep {{ version }}
    - ocamldebug -version | grep {{ version }}
    - ocamldep -version | grep {{ version }}
    - ocamllex -version | grep {{ version }}
    - ocamlmklib -version | grep {{ version }}
    - ocamlmktop -version | grep {{ version }}
    - ocamlobjinfo -help | grep FILES
    - ocamlobjinfo.byte -help | grep FILES
    - ocamlobjinfo.opt -help | grep FILES
    - ocamlopt -version | grep {{ version }}
    - ocamloptp -version | grep {{ version }}
    - ocamlprof -version | grep {{ version }}
    - ocamlrun -version | grep {{ version }}
    - ocamlyacc -version | grep {{ version }}

about:
  home: https://ocaml.org/
  license: LGPL-2.1-only WITH OCaml-LGPL-linking-exception
  license_family: LGPL
  license_file: LICENSE
  summary: Objective Caml (OCaml) is an implementation of the ML language.
  description: |
    OCaml is an implementation of the ML language, based on the Caml Light
    dialect extended with a complete class-based object system and a powerful
    module system in the style of Standard ML.

    OCaml comprises two compilers. One generates bytecode which is then
    interpreted by a C program. This compiler runs quickly, generates compact
    code with moderate memory requirements, and is portable to essentially any
    32 or 64 bit Unix platform. Performance of generated programs is quite good
    for a bytecoded implementation.  This compiler can be used either as a
    standalone, batch-oriented compiler that produces standalone programs, or as
    an interactive, toplevel-based system.

    The other compiler generates high-performance native code for a number of
    processors. Compilation takes longer and generates bigger code, but the
    generated programs deliver excellent performance, while retaining the
    moderate memory requirements of the bytecode compiler.
  doc_url: https://ocaml.org/docs/
  dev_url: https://github.com/ocaml/ocaml

extra:
  recipe-maintainers:
    - peterjc
    - isuruf
    - dslarm
