schema_version: 1

context:
  build_num: 1
  name: ocaml
  version: 5.4.0
  flexdll_version: 0.44
  dot: ${{ "./" if unix }}
  library: ${{ "Library/" if not unix }}
  m2: ${{ "m2-" if not unix }}
  sh: ${{ "sh" if unix else "bat" }}
  so: ${{ "so" if unix else "dll" }}

recipe:
  name: ocaml
  version: ${{ version }}

source:
  - url: https://github.com/ocaml/ocaml/archive/refs/tags/${{ version }}.tar.gz
    sha256: 4ab55ac30d247e20f35df20a9f7596e5eb5f92fbbd0f8e3e54838bbc3edf931e
  - if: win
    then:
      url: https://github.com/ocaml/flexdll/archive/refs/tags/${{ flexdll_version }}.tar.gz
      sha256: b7c6a92286f1f3065324d51083dcb16eec436a4e6e3b8df7cf836b6d7a8b9491
      target_directory: flexdll

build:
  number: ${{ build_num }}

outputs:
  # ============================================================================
  # MULTI-OUTPUT ARCHITECTURE:
  #
  # Output 1: ocaml (metapackage, all platforms)
  #   - Depends on ocaml_${{ target_platform }}
  #
  # Output 2: ocaml_${{ target_platform }} (platform implementation)
  #   - Native build: when build_platform == target_platform
  #   - Cross build: when build_platform != target_platform
  #
  # Output 3: ocaml-cross-compiler_${{ cross_target }}
  #   - Built on native platforms (linux-64, osx-64) only
  #   - Skipped on cross-platforms
  #
  # BUILD ORDER on linux-64:
  #   1. ocaml_linux-64 (native build)
  #   2. ocaml-cross-compiler_linux-aarch64 (depends on ocaml_linux-64)
  #   3. ocaml-cross-compiler_linux-ppc64le (depends on ocaml_linux-64)
  #   4. ocaml metapackage
  #
  # BUILD ORDER on linux-aarch64:
  #   1. ocaml_linux-aarch64 (self-sufficient, 3-stage fallback if needed)
  #   2. ocaml metapackage
  # ============================================================================

  # ============================================================================
  # Output 1: User-facing metapackage (all platforms)
  # ============================================================================
  - package:
      name: ocaml
    build:
      script: echo "META package"
      string: ${{ PKG_BUILDNUM }}
    requirements:
      run_exports:
        - ${{ pin_subpackage("ocaml", exact=True) }}
      run:
        - ${{ pin_subpackage("ocaml_" ~target_platform, exact=True) }}
    tests:
      - script:
          - if: arm64
            then:
              - echo "No test on non-emulated platfrom"
            else:
              - ocaml -version
              - ocamlc -version
              - ocamlopt -version
    about:
      summary: OCaml compiler (metapackage)
      license: LGPL-2.1-only WITH OCaml-LGPL-linking-exception
      license_family: LGPL
      license_file: LICENSE

  # ============================================================================
  # Output 2: Platform implementation (native OR cross-compiled)
  # ============================================================================
  - package:
      name: ocaml_${{ target_platform }}
    build:
      script:
        content:
          - if: unix
            then: source "${RECIPE_DIR}"/build.sh
            else: call "%RECIPE_DIR%\build.bat"
        env:
          SKIP_MAKE_TESTS: 1
      dynamic_linking:
        missing_dso_allowlist:
          - if: osx
            then:
              - /usr/lib/libSystem.B.dylib
          - if: not unix
            then:
              - C:/Windows/system32/SHLWAPI.dll
              - C:/Windows/system32/VERSION.dll
      prefix_detection:
        force_file_type:
          text:
            - lib/ocaml/ld.conf
            - lib/ocaml/Makefile.config
            - lib/ocaml/runtime-launch-info
        ignore:
          # Bytecode files - binary format, relocation corrupts them
          - lib/ocaml/**/*.cmo
          - lib/ocaml/**/*.cma
          - lib/ocaml/**/*.cmi
          - lib/ocaml/**/*.cmx
          - lib/ocaml/**/*.cmt
          - lib/ocaml/**/*.cmti
          # Bytecode executables with #!/usr/bin/env ocamlrun shebang
          - bin/ocaml
          - bin/ocamlc.byte
          - bin/ocamlcmt
          - bin/ocamlcp
          - bin/ocamldebug
          - bin/ocamldoc
          - bin/ocamldep.byte
          - bin/ocamllex.byte
          - bin/ocamlmklib
          - bin/ocamlmktop
          - bin/ocamlobjinfo.byte
          - bin/ocamlopt.byte
          - bin/ocamloptp
          - bin/ocamlprof
          # Native binaries - use OCAMLLIB env var instead of relocation
          - bin/ocamlc.opt
          - bin/ocamlopt.opt
          - bin/ocamldep.opt
          - bin/ocamllex.opt
          - bin/ocamlobjinfo.opt
          - bin/ocamldoc.opt
    requirements:
      build:
        - ${{ compiler('c') }}
        - ${{ stdlib('c') }}
        - ${{ m2 }}bash >=5.2
        - ${{ m2 }}file
        - ${{ m2 }}findutils
        - ${{ m2 }}gawk
        - ${{ m2 }}grep
        - ${{ m2 }}make
        - ${{ m2 }}sed
        - binutils
        - if: not unix
          then:
            - ${{ m2 }}coreutils
            - ${{ m2 }}diffutils
            - ${{ m2 }}which
        - if: osx
          then:
            - lld
            - llvm-tools
        - if: build_platform != target_platform and match(version, ">=5.4") and build_num > 1
          then:
            - ${{ pin_subpackage("ocaml-cross-compiler_" ~target_platform, exact=True) }}
      host:
        - zstd
      run:
        - zstd
    tests:
      - package_contents:
          bin:
            - if: unix
              then:
                - conda-ocaml-ar
                - conda-ocaml-as
                - conda-ocaml-cc
                - conda-ocaml-mkdll
                - conda-ocaml-mkexe
                - conda-ocaml-ranlib
            - ocaml
            - ocamlc
            - ocamlc.byte
            - ocamlc.opt
            - ocamlcmt
            - ocamlcp
            - ocamldep
            - ocamldep.byte
            - ocamldep.opt
            - ocamllex
            - ocamllex.byte
            - ocamllex.opt
            - ocamlmklib
            - ocamlmktop
            - ocamlobjinfo
            - ocamlobjinfo.byte
            - ocamlobjinfo.opt
            - ocamlopt
            - ocamlopt.byte
            - ocamlopt.opt
            - ocamloptp
            - ocamlprof
            - ocamlrun
            - ocamlyacc
            - if: build_platform == target_platform
              then:
                - ocamldebug
                - ocamldoc
                - ocamldoc.opt
            - if: unix
              then:
                - ocamlruni
              else:
                - flexlink
                - flexlink.byte
                - flexlink.opt
          files:
            - etc/conda/activate.d/ocaml_activate.${{ sh }}
            - etc/conda/deactivate.d/ocaml_deactivate.${{ sh }}
            - ${{ library }}lib/ocaml/ld.conf
            - ${{ library }}lib/ocaml/libasmrun.a
            - ${{ library }}lib/ocaml/Makefile.config
            - ${{ library }}lib/ocaml/runtime-launch-info
            - ${{ library }}lib/ocaml/*.a
            - ${{ library }}lib/ocaml/*.cma
            - ${{ library }}lib/ocaml/*.cmi
            - ${{ library }}lib/ocaml/*.cmo
            - ${{ library }}lib/ocaml/*.cmt
            - ${{ library }}lib/ocaml/*.cmti
            - ${{ library }}lib/ocaml/*.cmx
            - ${{ library }}lib/ocaml/*.cmxa
            - ${{ library }}lib/ocaml/*.ml
            - ${{ library }}lib/ocaml/*.mli
            - ${{ library }}lib/ocaml/*.o
            - ${{ library }}lib/ocaml/caml/*.h
            - ${{ library }}lib/ocaml/compiler-libs/*
            - ${{ library }}lib/ocaml/dynlink/*
            - ${{ library }}lib/ocaml/profiling/*
            - ${{ library }}lib/ocaml/str/*
            - ${{ library }}lib/ocaml/threads/*
            - ${{ library }}lib/ocaml/unix/*
            - ${{ library }}lib/ocaml/stublibs/dll*.${{ so }}
            - ${{ library }}share/doc/ocaml/*
            - if: (build_platform == target_platform) and unix
              then:
                - ${{ library }}lib/ocaml/ocamldoc/*
                - share/man/man{1,3}/*

      # Environment and resource file paths (no build-time paths leaked)
      - script:
          - cd testing && ${{ dot }}test-env-paths.${{ sh }}
        files:
          recipe:
            - testing/test-env-paths.${{ sh }}
        requirements:
          run:
            - binutils
            - if: not arm64
              then:
                - ${{ m2 }}grep

      # OCAML config
      - script:
          - if: unix and not arm64
            then:
              - cd testing && ./test-config.sh
            else:
              - echo ""
        files:
          recipe:
            - testing/test-config.sh
        requirements:
          run:
            - binutils_impl_${{ target_platform }}
            - if: not arm64
              then:
                - ${{ m2 }}grep

      # Cross-compiled binary architecture verification
      - script:
          - if: build_platform != target_platform
            then:
              - cd testing && ${{ dot }}test-cross-arch.${{ sh }} ${{ target_platform }}
            else:
              - echo "Native build - skipping cross-arch check"
        files:
          recipe:
            - testing/test-cross-arch.${{ sh }}
        requirements:
          run:
            - binutils

      # Tool versions (skip on ARM64 cross-compiled - can't run binaries under QEMU)
      - script:
          - if: arm64
            then:
              - echo "Skipping tool version tests"
            else:
              - cd testing && ${{ dot }}test-tool-versions.${{ sh }} ${{ version }}
        files:
          recipe:
            - testing/test-tool-versions.${{ sh }}
        requirements:
          run:
            - ${{ m2 }}grep

      # Native-only tools (ocamldoc, ocamldebug - only on native builds)
      - script:
          - if: (build_platform == target_platform) and unix
            then: cd testing && ${{ dot }}test-native-only-tools.${{ sh }} ${{ version }}
            else: echo "Skipping native-only tools (cross-build or Windows)"
        files:
          recipe:
            - testing/test-native-only-tools.${{ sh }}
        requirements:
          run:
            - ${{ m2 }}grep

      # Compilation tests (bytecode, native, multi-file)
      - script:
          - if: build_platform != target_platform
            then:
              - echo "Skipping compilation tests (cross-compiled package, QEMU limitation)"
            else:
              - cd testing && ${{ dot }}test-compilation.${{ sh }} ${{ version }}
          - if: not unix
            then: |
              printf 'print_endline "Hello World"\n' > hi.ml
              ocamlc -o hi.exe hi.ml && hi.exe | grep Hello && rm hi.exe
          - echo ""
        files:
          recipe:
            - testing/test-compilation.${{ sh }}
        requirements:
          run:
            - ${{ c_compiler }}_impl_${{ target_platform }} >=${{ c_compiler_version }}
            - ${{ m2 }}file
            - ${{ m2 }}grep
            - if: osx
              then:
                - lld >=${{ c_compiler_version }}
                - llvm-tools >=${{ c_compiler_version }}

      # CONDA_OCAML_* toolchain variable tests
      - script:
          - if: build_platform == target_platform
            then:
              - cd testing && ${{ dot }}test-toolchain-vars.${{ sh }}
            else:
              - echo "Toolchain var tests only on native builds"
        files:
          recipe:
            - testing/test-toolchain-vars.${{ sh }}
        requirements:
          run:
            - ${{ c_compiler }}_impl_${{ target_platform }} >=${{ c_compiler_version }}
            - ${{ m2 }}grep
            - if: osx
              then:
                - lld >=${{ c_compiler_version }}
                - llvm-tools >=${{ c_compiler_version }}
    about:
      summary: OCaml compilers for ${{ target_platform }}
      license: LGPL-2.1-only WITH OCaml-LGPL-linking-exception
      license_family: LGPL
      license_file: LICENSE

  # ============================================================================
  # Output 3: Cross-compiler (built on native platform, targets cross_target)
  # ============================================================================
  - package:
      name: ocaml-cross-compiler_${{ cross_target }}
    build:
      # Build only when:
      # 1. We're on the platform that builds this cross-compiler (build_platform == cross_build)
      # 2. This is a native build, not a cross-build job (build_platform == target_platform)
      # 3. Unix only (no Windows cross-compilation)
      skip: (build_platform != cross_build) or (build_platform != target_platform) or not unix
      dynamic_linking:
        missing_dso_allowlist:
          - if: linux
            then:
              - ${{ cross_linker }}
      prefix_detection:
        force_file_type:
          text:
            - lib/ocaml-cross-compilers/${{ triplet_target }}/lib/ocaml/ld.conf
            - lib/ocaml-cross-compilers/${{ triplet_target }}/lib/ocaml/Makefile.config
            - lib/ocaml-cross-compilers/${{ triplet_target }}/lib/ocaml/target_runtime-launch-info
        ignore:
          - lib/ocaml-cross-compilers/${{ triplet_target }}/lib/ocaml/**/*.cmo
          - lib/ocaml-cross-compilers/${{ triplet_target }}/lib/ocaml/**/*.cma
          - lib/ocaml-cross-compilers/${{ triplet_target }}/lib/ocaml/**/*.cmi
          - lib/ocaml-cross-compilers/${{ triplet_target }}/lib/ocaml/**/*.cmx
          - lib/ocaml-cross-compilers/${{ triplet_target }}/lib/ocaml/**/*.cmt
          - lib/ocaml-cross-compilers/${{ triplet_target }}/lib/ocaml/**/*.cmti
    requirements:
      build:
        - ${{ c_compiler }}_impl_${{ cross_target }} ${{ c_compiler_version }}.*
        - ${{ c_stdlib }}_${{ cross_target }} ==${{ c_stdlib_version }}
        - ${{ compiler('c') }}
        - ${{ stdlib('c') }}
        - ${{ m2 }}bash >=5.2
        - ${{ m2 }}file
        - ${{ m2 }}findutils
        - ${{ m2 }}gawk
        - ${{ m2 }}grep
        - ${{ m2 }}make
        - ${{ m2 }}sed
        - ${{ m2 }}tar
        - binutils
        - ocaml_${{ cross_build }} ==${{ version }}
      host:
        - zstd
        - if: osx
          then:
            - lld ${{ c_compiler_version }}.*
            - llvm-tools ${{ c_compiler_version }}.*
    tests:
      - package_contents:
          bin:
            - ${{ triplet_target }}-ocamlc
            - ${{ triplet_target }}-ocamldep
            - ${{ triplet_target }}-ocamlobjinfo
            - ${{ triplet_target }}-ocamlopt
          lib:
            - ocaml-cross-compilers/${{ triplet_target }}/lib/ocaml/libasmrun.a
            - ocaml-cross-compilers/${{ triplet_target }}/lib/ocaml/*.a
          files:
            - lib/ocaml-cross-compilers/${{ triplet_target }}/lib/ocaml/stublibs/dll*.${{ so }}
            - lib/ocaml-cross-compilers/${{ triplet_target }}/lib/ocaml/runtime-launch-info
            - lib/ocaml-cross-compilers/${{ triplet_target }}/lib/ocaml/*.cma
            - lib/ocaml-cross-compilers/${{ triplet_target }}/lib/ocaml/*.cmi
            - lib/ocaml-cross-compilers/${{ triplet_target }}/lib/ocaml/*.cmo
            - lib/ocaml-cross-compilers/${{ triplet_target }}/lib/ocaml/*.cmx
            - lib/ocaml-cross-compilers/${{ triplet_target }}/lib/ocaml/*.cmxa
            - lib/ocaml-cross-compilers/${{ triplet_target }}/lib/ocaml/*.o
      - script: |
          echo "Testing ${{ cross_target }} cross-compilers..."
          echo "  ocamlc..." && ${{ triplet_target }}-ocamlc -version | grep ${{ version }}
          echo "  ocamldep..." && ${{ triplet_target }}-ocamldep -version | grep ${{ version }}
          echo "  ocamlobjinfo..." && ${{ triplet_target }}-ocamlobjinfo -help | grep -q FILES
          echo "  ocamlopt..." && ${{ triplet_target }}-ocamlopt -version | grep ${{ version }}
        requirements:
          run:
            - grep
      - script:
          - cd testing && ${{ dot }}test-cross-compilers.${{ sh }} ${{ version }} ${{ build_platform }} ${{ target_platform }}
        files:
          recipe:
            - testing/test-cross-compilers.${{ sh }}
        requirements:
          run:
            - ${{ c_compiler }}_impl_${{ target_platform }} >=${{ c_compiler_version }}
            - ${{ m2 }}grep
            - if: osx
              then:
                - lld >=${{ c_compiler_version }}
                - llvm-tools >=${{ c_compiler_version }}
    about:
      summary: OCaml cross-compiler for ${{ cross_target }}
      license: LGPL-2.1-only WITH OCaml-LGPL-linking-exception
      license_family: LGPL
      license_file: LICENSE

about:
  homepage: https://ocaml.org/
  license: LGPL-2.1-only WITH OCaml-LGPL-linking-exception
  license_family: LGPL
  license_file: LICENSE
  summary: Objective Caml (OCaml) is an implementation of the ML language.
  description: |
    OCaml is an implementation of the ML language, based on the Caml Light
    dialect extended with a complete class-based object system and a powerful
    module system in the style of Standard ML.

    OCaml comprises two compilers. One generates bytecode which is then
    interpreted by a C program. This compiler runs quickly, generates compact
    code with moderate memory requirements, and is portable to essentially any
    32 or 64 bit Unix platform. Performance of generated programs is quite good
    for a bytecoded implementation.  This compiler can be used either as a
    standalone, batch-oriented compiler that produces standalone programs, or as
    an interactive, toplevel-based system.

    The other compiler generates high-performance native code for a number of
    processors. Compilation takes longer and generates bigger code, but the
    generated programs deliver excellent performance, while retaining the
    moderate memory requirements of the bytecode compiler.
  documentation: https://ocaml.org/docs/
  repository: https://github.com/ocaml/ocaml

extra:
  feedstock-name: ocaml
  recipe-maintainers:
    - isuruf
    - dslarm
    - MementoRC
