context:
  build_number: 0
  name: ocaml
  version: 5.4.0
  flexdll_version: 0.44
  dot: ${{ "./" if unix }}
  library: ${{ "Library/" if not unix }}
  m2: ${{ "m2-" if not unix }}
  sh: ${{ "sh" if unix else "bat" }}
  so: ${{ "so" if unix else "dll" }}
  xt: ${{ "" if unix else ".exe" }}
  c_compiler_key: ${{ "m2w64_c" if CC_ == "mingw" else "c" }}                                          
  target_triplet: >-
    ${{
      "x86_64-w64-mingw32"          if not unix and CC_ == "mingw" else                                                 
      "x86_64-pc-windows"           if not unix and CC_ != "mingw" else
      "unknown"
    }}
  
package:
  name: ocaml
  version: ${{ version }}

source:
  - url: https://github.com/ocaml/ocaml/archive/refs/tags/${{ version }}.tar.gz
    sha256: 4ab55ac30d247e20f35df20a9f7596e5eb5f92fbbd0f8e3e54838bbc3edf931e
    patches:
      # Fix header include order bug where atomic_load_acquire/atomic_store_release
      # macros are undefined when mlvalues.h is included before platform.h.
      # The macros were guarded by CAML_INTERNALS, but public headers include
      # camlatomic.h, setting the include guard before CAML_INTERNALS is defined.
      - patches/fix-camlatomic-include-order.patch
  - if: not unix
    then:
      url: https://github.com/ocaml/flexdll/archive/refs/tags/${{ flexdll_version }}.tar.gz
      sha256: b7c6a92286f1f3065324d51083dcb16eec436a4e6e3b8df7cf836b6d7a8b9491
      target_directory: flexdll
  - if: not unix and CC_ != "mingw"
    then:
      url: https://github.com/ocaml/winpthreads/archive/d635af4d9bcce7f268b3e3c44f414611bbc66381.tar.gz
      sha256: f390e421dfbc3e5182cbe98832f23c946863349719db9a5439d578875a262193
      target_directory: winpthreads

build:
  number: ${{ build_number }}
  string: ${{ CC_ ~ "_" if CC_ }}h${{ hash }}_${{ build_number }}
  variant:                                                                                                                 
    down_prioritize_variant: ${{ 0 if CC_ == "mingw" else 1 }}                                                             
  script:
    env:
      SKIP_MAKE_TESTS: 1
      TARGET_TRIPLET: ${{ target_triplet }}
  dynamic_linking:
    missing_dso_allowlist:
      - if: linux
        then:
          - ld-linux-aarch64.${{ so }}.1  # PPC64LE cross-compiler
          - ld64.${{ so }}.2              # AARCH64 cross-compiler
      - if: osx
        then:
          - /usr/lib/libSystem.B.dylib
      - if: not unix
        then:
          - C:/Windows/system32/SHLWAPI.dll
          - C:/Windows/system32/VERSION.dll
  prefix_detection:
    force_file_type:
      text:
        # These are actual text files that need prefix relocation
        - lib/ocaml/ld.conf
        - lib/ocaml/Makefile.config
        - lib/ocaml/runtime-launch-info
        - lib/ocaml-cross-compilers/*/lib/ocaml/ld.conf
        - lib/ocaml-cross-compilers/*/lib/ocaml/Makefile.config
        - lib/ocaml-cross-compilers/*/lib/ocaml/runtime-launch-info
    ignore:
      # Only ignore bytecode files (binary format, relocation corrupts them)
      - lib/ocaml/**/*.{cma,cmi,cmo,cmt,cmti,cmx}
      # Bytecode executables - MUST ignore to avoid corrupting binary data
      # These use #!/usr/bin/env ocamlrun shebang which doesn't need relocation
      - bin/ocaml
      - bin/ocaml{c,dep,lex,objinfo,opt}.byte
      - bin/ocaml{cmt,cp,debug,doc,mklib,mktop,optp,prof}
      - if: (linux or osx) and x86_64
        then:
          - lib/ocaml-cross-compilers/*/lib/ocaml/**/*.{cma,cmi,cmo,cmt,cmti,cmx}
          # Bytecode executables - MUST ignore to avoid corrupting binary data
          # These use #!/usr/bin/env ocamlrun shebang which doesn't need relocation
          - lib/ocaml-cross-compilers/*/bin/ocaml
          - lib/ocaml-cross-compilers/*/bin/ocaml{c,dep,lex,objinfo,opt}.byte
          - lib/ocaml-cross-compilers/*/bin/ocaml{cmt,cp,debug,doc,mklib,mktop,optp,prof}

requirements:
  run_exports:
    weak:
      - ${{ pin_subpackage("ocaml", upper_bound="x.x.x") }}
    strong:
      - if: CC_ == "mingw"
        then:
          - m2w64-gcc-libs
      - if: CC_ == "vs"
        then:
          - vc >=${{ vc }}
  build:
    - if: CC_ == "mingw"
      then:
        - ${{ compiler("m2w64_c") }}
        - ${{ stdlib("m2w64_c") }}
      else:
        - ${{ compiler("c") }}
        - ${{ stdlib("c") }}
    - ${{ m2 }}bash >=5.2
    - ${{ m2 }}file
    - ${{ m2 }}findutils
    - ${{ m2 }}gawk
    - ${{ m2 }}grep
    - ${{ m2 }}make
    - ${{ m2 }}sed
    - ${{ m2 }}tar
    - binutils
    - if: linux and x86_64
      then:
        - ${{ c_compiler }}_impl_linux-aarch64 ${{ c_compiler_version }}.*
        - ${{ c_compiler }}_impl_linux-ppc64le ${{ c_compiler_version }}.*
        - ${{ c_stdlib }}_linux-aarch64 =${{ c_stdlib_version }}
        - ${{ c_stdlib }}_linux-ppc64le =${{ c_stdlib_version }}
        - binutils_impl_linux-aarch64
        - binutils_impl_linux-ppc64le
    - if: osx and x86_64
      then:
        - ${{ c_compiler }}_impl_osx-arm64 ${{ c_compiler_version }}.*
    - if: not unix
      then:
        - ${{ m2 }}coreutils
        - ${{ m2 }}diffutils
        - ${{ m2 }}which
    - if: aarch64 or ppc64le or arm64
      then:
        - ocaml >=5.3
        - zstd
    - if: osx
      then:
        - lld ${{ c_compiler_version }}.*
        - llvm-tools ${{ c_compiler_version }}.*
  host:
    - zstd
  run:
    - zstd
    - if: CC_ == "mingw"
      then:
        - ${{ m2w64_c_compiler }}_${{ target_platform }}
      else:
        - c-compiler
    - if: osx
      then:
        - lld >=${{ c_compiler_version }}
        - llvm-tools >=${{ c_compiler_version }}
    - if: unix or (CC_ == "mingw")
      then:
        - binutils_impl_${{ target_platform }}

tests:
  - package_contents:
      strict: true
      bin:
        - conda-ocaml-{ar,as,cc,ld,ranlib}
        - if: unix
          then:
            - conda-ocaml-{mkdll,mkexe}
          else:
            - conda-ocaml-windres
        - ocaml
        - ocaml{c,dep,lex,objinfo,opt,mklib,yacc}
        - ocaml{c,dep,lex,objinfo,opt,mklib,yacc}.opt
        - ocaml{c,dep,lex,objinfo,opt}.byte
        - ocaml{cmt,cp,mktop,optp,prof,run,rund}
        - if: build_platform == target_platform
          then:
            - ocamldebug
            - ocamldoc
            - ocamldoc.opt
        - if: linux and x86_64
          then:
            - aarch64-conda-linux-gnu-ocaml{c,dep,lex,objinfo,opt,mklib,yacc}
            - aarch64-conda-linux-gnu-ocaml{c,dep,lex,objinfo,opt,mklib,yacc}.opt
            - powerpc64le-conda-linux-gnu-ocaml{c,dep,lex,objinfo,opt,mklib,yacc}
            - powerpc64le-conda-linux-gnu-ocaml{c,dep,lex,objinfo,opt,mklib,yacc}.opt
        - if: osx and x86_64
          then:
            - arm64-apple-darwin20.0.0-ocaml{c,dep,lex,objinfo,opt,mklib,yacc}
            - arm64-apple-darwin20.0.0-ocaml{c,dep,lex,objinfo,opt,mklib,yacc}.opt
        - if: unix or (CC_ != "mingw")
          then:
            - ocamlruni
        - if: (CC_ == "vs")
          then:
            - default_amd64.manifest
        - if: not unix
          then:
            - flexlink
            - flexlink.byte
            - flexlink.opt
      files:
        - etc/conda/activate.d/ocaml_activate.${{ sh }}
        - etc/conda/deactivate.d/ocaml_deactivate.${{ sh }}
        - etc/conda/test-files/*
        
        - ${{ library }}lib/ocaml/expunge${{ xt }}
        - ${{ library }}lib/ocaml/ld.conf
        - ${{ library }}lib/ocaml/Makefile.config
        - ${{ library }}lib/ocaml/runtime-launch-info
        - ${{ library }}lib/ocaml/sys.ml.in
        - ${{ library }}lib/ocaml/*.{a,cma,cmi,cmo,cmt,cmti,cmx,cmxa,ml,mli,o}
        - ${{ library }}lib/ocaml/caml/domain_state.tbl
        - ${{ library }}lib/ocaml/caml/*.h
        - ${{ library }}lib/ocaml/{compiler-libs,dynlink,profiling,runtime_events,stdlib,str,threads,unix}/*
        - ${{ library }}lib/ocaml/stublibs/dll*.${{ so }}
        - ${{ library }}share/doc/ocaml/*
        - if: build_platform == target_platform
          then:
            - ${{ library }}share/man/man{1,3}/*
            - ${{ library }}lib/ocaml/ocamldoc/*
          else:
            - share/man/man1/*
        - if: unix or (CC_ == "mingw")
          then:
            - ${{ library }}lib/ocaml/libasmrun.a
          else:
            - ${{ library }}lib/ocaml/flexdll/flexdll_initer_msvc64.obj
            - ${{ library }}lib/ocaml/flexdll/flexdll_msvc64.obj
            - ${{ library }}lib/ocaml/libasm{run,rund,runi}.lib
            - ${{ library }}lib/ocaml/libcaml{run,rund,runi}.lib
            - ${{ library }}lib/ocaml/libcamlruntime_{eventsbyt,eventsnat}.lib
            - ${{ library }}lib/ocaml/libcamlstr{byt,nat}.lib
            - ${{ library }}lib/ocaml/libcomprmarsh.lib
            - ${{ library }}lib/ocaml/libthread{s,snat}.lib
            - ${{ library }}lib/ocaml/libunix{byt,nat}.lib
            - ${{ library }}lib/ocaml/std_exit.obj
            - ${{ library }}lib/ocaml/stdlib.lib
        - if: unix
          then:
            - ${{ library }}lib/ocaml/libasmrun_shared.so
            - ${{ library }}lib/ocaml/libcamlrun_shared.so
        - if: linux and x86_64
          then:
            - lib/ocaml-cross-compilers/{aarch64,powerpc64le}-conda-linux-gnu/bin/ocaml{c,dep,lex,objinfo,opt,mklib,yacc}
            - lib/ocaml-cross-compilers/{aarch64,powerpc64le}-conda-linux-gnu/bin/ocaml{c,dep,lex,objinfo,opt,mklib,yacc}.opt
            - lib/ocaml-cross-compilers/{aarch64,powerpc64le}-conda-linux-gnu/lib/ocaml/expunge
            - lib/ocaml-cross-compilers/{aarch64,powerpc64le}-conda-linux-gnu/lib/ocaml/ld.conf
            - lib/ocaml-cross-compilers/{aarch64,powerpc64le}-conda-linux-gnu/lib/ocaml/libasmrun.a
            - lib/ocaml-cross-compilers/{aarch64,powerpc64le}-conda-linux-gnu/lib/ocaml/libasmrun_shared.so
            - lib/ocaml-cross-compilers/{aarch64,powerpc64le}-conda-linux-gnu/lib/ocaml/libcamlrun_shared.so
            - lib/ocaml-cross-compilers/{aarch64,powerpc64le}-conda-linux-gnu/lib/ocaml/Makefile.config
            - lib/ocaml-cross-compilers/{aarch64,powerpc64le}-conda-linux-gnu/lib/ocaml/runtime-launch-info
            - lib/ocaml-cross-compilers/{aarch64,powerpc64le}-conda-linux-gnu/lib/ocaml/sys.ml.in
            - lib/ocaml-cross-compilers/{aarch64,powerpc64le}-conda-linux-gnu/lib/ocaml/*.{a,cma,cmi,cmo,cmt,cmti,cmx,cmxa,ml,mli,o}
            - lib/ocaml-cross-compilers/{aarch64,powerpc64le}-conda-linux-gnu/lib/ocaml/caml/domain_state.tbl
            - lib/ocaml-cross-compilers/{aarch64,powerpc64le}-conda-linux-gnu/lib/ocaml/caml/*.h
            - lib/ocaml-cross-compilers/{aarch64,powerpc64le}-conda-linux-gnu/lib/ocaml/{compiler-libs,dynlink,profiling,runtime_events,stdlib,str,threads,unix}/*
            - lib/ocaml-cross-compilers/{aarch64,powerpc64le}-conda-linux-gnu/lib/ocaml/stublibs/dll*.${{ so }}
            - lib/ocaml-cross-compilers/{aarch64,powerpc64le}-conda-linux-gnu/share/doc/ocaml/*
            - lib/ocaml-cross-compilers/{aarch64,powerpc64le}-conda-linux-gnu/share/man/man1/*
        - if: osx and x86_64
          then:
            - lib/ocaml-cross-compilers/arm64-apple-darwin20.0.0/bin/ocaml{c,dep,lex,objinfo,opt,mklib,yacc}
            - lib/ocaml-cross-compilers/arm64-apple-darwin20.0.0/bin/ocaml{c,dep,lex,objinfo,opt,mklib,yacc}.opt
            - lib/ocaml-cross-compilers/arm64-apple-darwin20.0.0/lib/ocaml/expunge
            - lib/ocaml-cross-compilers/arm64-apple-darwin20.0.0/lib/ocaml/ld.conf
            - lib/ocaml-cross-compilers/arm64-apple-darwin20.0.0/lib/ocaml/libasmrun.a
            - lib/ocaml-cross-compilers/arm64-apple-darwin20.0.0/lib/ocaml/libasmrun_shared.so
            - lib/ocaml-cross-compilers/arm64-apple-darwin20.0.0/lib/ocaml/libcamlrun_shared.so
            - lib/ocaml-cross-compilers/arm64-apple-darwin20.0.0/lib/ocaml/Makefile.config
            - lib/ocaml-cross-compilers/arm64-apple-darwin20.0.0/lib/ocaml/runtime-launch-info
            - lib/ocaml-cross-compilers/arm64-apple-darwin20.0.0/lib/ocaml/sys.ml.in
            - lib/ocaml-cross-compilers/arm64-apple-darwin20.0.0/lib/ocaml/*.{a,cma,cmi,cmo,cmt,cmti,cmx,cmxa,ml,mli,o}
            - lib/ocaml-cross-compilers/arm64-apple-darwin20.0.0/lib/ocaml/caml/domain_state.tbl
            - lib/ocaml-cross-compilers/arm64-apple-darwin20.0.0/lib/ocaml/caml/*.h
            - lib/ocaml-cross-compilers/arm64-apple-darwin20.0.0/lib/ocaml/{compiler-libs,dynlink,profiling,runtime_events,stdlib,str,threads,unix}/*
            - lib/ocaml-cross-compilers/arm64-apple-darwin20.0.0/lib/ocaml/stublibs/dll*.${{ so }}
            - lib/ocaml-cross-compilers/arm64-apple-darwin20.0.0/share/doc/ocaml/*
            - lib/ocaml-cross-compilers/arm64-apple-darwin20.0.0/share/man/man1/*

  # Environment and resource file path validation
  - script:
      - cd testing && ${{ dot }}test-env-paths.${{ sh }}
    files:
      recipe:
        - testing/test-env-paths.${{ sh }}
    requirements:
      run:
        - binutils
        - if: not arm64
          then:
            - ${{ m2 }}grep

  # OCAML config
  - script:
      - if: unix and not arm64
        then:
          - cd testing && ./test-config.sh
        else:
          - echo ""
    files:
      recipe:
        - testing/test-config.sh
    requirements:
      run:
        - ${{ m2 }}grep

  # Cross-compiled binary architecture verification
  - script:
      - if: build_platform != target_platform
        then:
          - cd testing && ${{ dot }}test-cross-arch.${{ sh }} ${{ target_platform }}
        else:
          - echo "Native build - skipping cross-arch check"
    files:
      recipe:
        - testing/test-cross-arch.${{ sh }}

  # Tool version checks (all platforms)
  # Skip on cross-compiled platforms - QEMU emulation has limitations
  - script:
      content:
        - if: arm64
          then:
            - echo "Skipping tool version tests"
          else:
            - cd testing && ${{ dot }}test-tool-versions.${{ sh }} ${{ version }}
    files:
      recipe:
        - testing/test-tool-versions.${{ sh }}
    requirements:
      run:
        - ${{ m2 }}grep

  # Native-only tools (ocamldoc, ocamldebug)
  - script:
      content:
        - if: (build_platform == target_platform) and unix
          then: cd testing && ${{ dot }}test-native-only-tools.${{ sh }} ${{ version }}
          else: echo "Skipping native-only tools (cross-build or non-unix)"
    files:
      recipe:
        - testing/test-native-only-tools.${{ sh }}
    requirements:
      run:
        - ${{ m2 }}grep

  # Compilation tests (bytecode, native, multi-file)
  # Skip on cross-compiled platforms (aarch64, ppc64le, arm64) - QEMU emulation unstable
  - script:
      content:
        - if: build_platform != target_platform
          then: echo "Skipping compilation tests (cross-compiled package, QEMU limitation)"
          else:
            - cd testing && ${{ dot }}test-compilation.${{ sh }} ${{ version }}
    files:
      recipe:
        - testing/test-compilation.${{ sh }}
    requirements:
      run:
        - ${{ m2 }}file
        - ${{ m2 }}grep

  # Cross-compiler tests (linux-64 and osx-64 only)
  - script:
      content:
        - if: (linux and x86_64) or (osx and x86_64)
          then:
            - cd testing && ${{ dot }}test-cross-compilers.${{ sh }} ${{ version }} ${{ build_platform }} ${{ target_platform }}
            - ${{ dot }}test-prims-architecture.${{ sh }}
          else:
            - echo "Cross-compilers only tested on linux-64 and osx-64"
    files:
      recipe:
        - testing/test-cross-compilers.${{ sh }}
        - testing/test-prims-architecture.${{ sh }}
    requirements:
      run:
        - ${{ m2 }}grep
        - if: linux and x86_64
          then:
            - ${{ c_compiler }}_impl_linux-aarch64 >=${{ c_compiler_version }}
            - ${{ c_compiler }}_impl_linux-ppc64le >=${{ c_compiler_version }}
            - ${{ c_stdlib }}_linux-aarch64 >=${{ c_stdlib_version }}
            - ${{ c_stdlib }}_linux-ppc64le >=${{ c_stdlib_version }}
            - binutils_impl_linux-aarch64
            - binutils_impl_linux-ppc64le
            - file
            - qemu-execve-aarch64
            - qemu-execve-ppc64le
        - if: osx and x86_64
          then:
            - ${{ c_compiler }}_impl_osx-arm64 >=${{ c_compiler_version }}

  # CONDA_OCAML_* toolchain variable tests
  - script:
      content:
        - if: build_platform == target_platform
          then: cd testing && ${{ dot }}test-toolchain-vars.${{ sh }}
          else: echo "Toolchain var tests only on native builds"
    files:
      recipe:
        - testing/test-toolchain-vars.${{ sh }}
    requirements:
      run:
        - ${{ m2 }}grep

about:
  homepage: https://ocaml.org/
  license: LGPL-2.1-only WITH OCaml-LGPL-linking-exception
  license_family: LGPL
  license_file: LICENSE
  summary: Objective Caml (OCaml) is an implementation of the ML language.
  description: |
    OCaml is an implementation of the ML language, based on the Caml Light
    dialect extended with a complete class-based object system and a powerful
    module system in the style of Standard ML.

    OCaml comprises two compilers. One generates bytecode which is then
    interpreted by a C program. This compiler runs quickly, generates compact
    code with moderate memory requirements, and is portable to essentially any
    32 or 64 bit Unix platform. Performance of generated programs is quite good
    for a bytecoded implementation.  This compiler can be used either as a
    standalone, batch-oriented compiler that produces standalone programs, or as
    an interactive, toplevel-based system.

    The other compiler generates high-performance native code for a number of
    processors. Compilation takes longer and generates bigger code, but the
    generated programs deliver excellent performance, while retaining the
    moderate memory requirements of the bytecode compiler.
  documentation: https://ocaml.org/docs/
  repository: https://github.com/ocaml/ocaml

extra:
  recipe-maintainers:
    - isuruf
    - dslarm
    - MementoRC
