schema_version: 1

context:
  build_num: 1
  name: ocaml
  version: 5.4.0
  flexdll_version: 0.44
  arm64_sdk: 11.0
  m2: ${{ "m2-" if not unix }}
  library: ${{ "Library/" if not unix }}
  sh: ${{ "sh" if unix else "bat" }}
  so: ${{ "so" if unix else "dll" }}

recipe:
  name: ocaml
  version: ${{ version }}

source:
  - url: https://github.com/ocaml/ocaml/archive/refs/tags/${{ version }}.tar.gz
    sha256: 4ab55ac30d247e20f35df20a9f7596e5eb5f92fbbd0f8e3e54838bbc3edf931e
  - if: win
    then:
      url: https://github.com/ocaml/flexdll/archive/refs/tags/${{ flexdll_version }}.tar.gz
      sha256: b7c6a92286f1f3065324d51083dcb16eec436a4e6e3b8df7cf836b6d7a8b9491
      target_directory: flexdll

build:
  number: ${{ build_num }}
  
outputs:
  # ============================================================================
  # MULTI-OUTPUT ARCHITECTURE:
  #
  # Output 1: ocaml (metapackage, all platforms)
  #   - Depends on ocaml_${{ target_platform }}
  #
  # Output 2: ocaml_${{ target_platform }} (platform implementation)
  #   - Native build: when build_platform == target_platform
  #   - Cross build: when build_platform != target_platform
  #     - Requires ocaml-cross-compiler_${{ target_platform }}
  #
  # Output 3: ocaml-cross-compiler_${{ cross_target }}
  #   - Built on native platforms (linux-64, osx-64) only
  #   - Skipped on cross-platforms
  #
  # BUILD ORDER on linux-64:
  #   1. ocaml_linux-64 (native build)
  #   2. ocaml-cross-compiler_linux-aarch64 (depends on ocaml_linux-64)
  #   3. ocaml-cross-compiler_linux-ppc64le (depends on ocaml_linux-64)
  #   4. ocaml-cross-compiler_linux-s390x (depends on ocaml_linux-64)
  #   5. ocaml metapackage
  #
  # BUILD ORDER on linux-aarch64:
  #   1. ocaml_linux-aarch64 (cross-build, uses ocaml-cross-compiler_linux-aarch64 from channel)
  #   2. ocaml metapackage
  # ============================================================================

  # ============================================================================
  # Output 1: User-facing metapackage (all platforms)
  # ============================================================================
  - package:
      name: ocaml
    build:
      # No skip - builds on all platforms
      string: ${{ PKG_BUILDNUM }}
    requirements:
      run_exports:
        - ${{ pin_subpackage("ocaml", exact=True) }}
      run:
        - ocaml_${{ target_platform }} ==${{ version }}
    tests:
      - script:
          - ocaml -version
          - ocamlc -version
          - ocamlopt -version
    about:
      summary: OCaml compiler (metapackage)
      license: LGPL-2.1-only WITH OCaml-LGPL-linking-exception
      license_file: LICENSE

  # ============================================================================
  # Output 2: Platform implementation (native OR cross-compiled)
  # ============================================================================
  - package:
      name: ocaml_${{ target_platform }}
    build:
      script:
        content: |
          echo "Building Native ocaml for ${{ target_platform }}"
          source "${RECIPE_DIR}"/build.${{ sh }}
        env:
          SKIP_MAKE_TESTS: 1
          ARM64_SDK: ${{ arm64_sdk }}
      dynamic_linking:
        missing_dso_allowlist:
          - if: osx
            then:
              - /usr/lib/libSystem.B.dylib
          - if: not unix
            then:
              - C:/Windows/system32/SHLWAPI.dll
              - C:/Windows/system32/VERSION.dll
      prefix_detection:
        force_file_type:
          text:
            - lib/ocaml/ld.conf
            - lib/ocaml/Makefile.config
            - lib/ocaml/runtime-launch-info
        ignore:
          # Bytecode files - binary format, relocation corrupts them
          - lib/ocaml/**/*.cmo
          - lib/ocaml/**/*.cma
          - lib/ocaml/**/*.cmi
          - lib/ocaml/**/*.cmx
          - lib/ocaml/**/*.cmt
          - lib/ocaml/**/*.cmti
          # Bytecode executables with #!/usr/bin/env ocamlrun shebang
          - bin/ocaml
          - bin/ocamlc.byte
          - bin/ocamlcmt
          - bin/ocamlcp
          - bin/ocamldebug
          - bin/ocamldoc
          - bin/ocamldep.byte
          - bin/ocamllex.byte
          - bin/ocamlmklib
          - bin/ocamlmktop
          - bin/ocamlobjinfo.byte
          - bin/ocamlopt.byte
          - bin/ocamloptp
          - bin/ocamlprof
    requirements:
      build:
        - ${{ compiler('c') }}
        - ${{ stdlib('c') }}
        - ${{ m2 }}bash >=5.2
        - ${{ m2 }}file
        - ${{ m2 }}findutils
        - ${{ m2 }}gawk
        - ${{ m2 }}grep
        - ${{ m2 }}make
        - ${{ m2 }}sed
        - binutils
        - pkgconfig
        # Windows-specific
        - if: not unix
          then:
            - ${{ m2 }}coreutils
            - ${{ m2 }}diffutils
            - ${{ m2 }}which
        # macOS-specific
        - if: osx
          then:
            - lld
            - llvm-tools
        # Cross-compiler for cross-builds (when build_platform != target_platform)
        # Note: Uses regular dependency (not pin_subpackage) because cross-compiler
        # is built on a different platform and won't be in the same recipe run
        - if: build_platform != target_platform
          then:
            - ocaml-cross-compiler_${{ target_platform }} ==${{ version }}
      host:
        - zstd
      run:
        - zstd
    tests:
      - package_contents:
          bin:
            - ocaml
            - ocamlc
            - ocamlc.byte
            - ocamlc.opt
            - ocamlcmt
            - ocamlcp
            - ocamldep
            - ocamldep.byte
            - ocamldep.opt
            - ocamllex
            - ocamllex.byte
            - ocamllex.opt
            - ocamlmklib
            - ocamlmktop
            - ocamlobjinfo
            - ocamlobjinfo.byte
            - ocamlobjinfo.opt
            - ocamlopt
            - ocamlopt.byte
            - ocamlopt.opt
            - ocamloptp
            - ocamlprof
            - ocamlrun
            - ocamlyacc
          lib:
            - ocaml/**/*.a
            - ocaml/stublibs/dll*.${{ so }}
          files:
            - ${{ library }}lib/ocaml/*.ml
            - ${{ library }}lib/ocaml/*.mli
            - ${{ library }}lib/ocaml/caml/*.h
            - ${{ library }}lib/ocaml/compiler-libs/*
            - ${{ library }}lib/ocaml/dynlink/*
            - ${{ library }}lib/ocaml/profiling/*
            - ${{ library }}lib/ocaml/str/*
            - ${{ library }}lib/ocaml/threads/*
            - ${{ library }}lib/ocaml/unix/*
            - ${{ library }}lib/ocaml/ocamldoc/*
            - if: unix
              then:
                - ${{ library }}share/doc/ocaml/*
                - share/man/man{1,3}/*
      - script:
          - echo "=== Env., Resource files ==="
          - if: unix
            then: |
              echo "${OCAMLLIB:-'UNSET'}" | grep ocaml > /dev/null && { echo "OCAMLLIB set"; }
              head -2 ${PREFIX}/lib/ocaml/runtime-launch-info | grep ${PREFIX} > /dev/null && { echo "runtime-launch-info clean"; }
              head -2 ${PREFIX}/lib/ocaml/ld.conf | grep ${PREFIX} > /dev/null && { echo "ld.conf clean"; }
              cat ${PREFIX}/lib/ocaml/Makefile.config | grep ${PREFIX} > /dev/null && { echo "Makefile.config clean"; }
              STDLIB_PATH=$(ocamlc.opt -config-var standard_library) && echo "standard_library=$STDLIB_PATH"
              CC_PATH=$(ocamlc.opt -config-var c_compiler) && echo "c_compiler=$CC_PATH"
            else: |
              echo "%OCAMLLIB%" | grep ocaml
              echo "%PATH%" | grep ocaml
          - echo "PREFIX/PATH tests passed"
        requirements:
          run:
            - ${{ m2 }}grep
      - script: |
          echo "Testing ocamlc..." && ocamlc -version | grep ${{ version }}
          echo "Testing ocamldep..." && ocamldep -version | grep ${{ version }}
          echo "Testing ocamllex..." && ocamllex -version | grep ${{ version }}
          echo "Testing ocamlrun..." && ocamlrun -version | grep ${{ version }}
          echo "Testing ocamlyacc..." && ocamlyacc -version | grep ${{ version }}

          echo "Testing ocaml..." && ocaml -version | grep ${{ version }}
          echo "Testing ocamlcp..." && ocamlcp -version | grep ${{ version }}
          echo "Testing ocamlmklib..." && ocamlmklib -version | grep ${{ version }}
          echo "Testing ocamlmktop..." && ocamlmktop -version | grep ${{ version }}
          echo "Testing ocamloptp..." && ocamloptp -version | grep ${{ version }}
          echo "Testing ocamlprof..." && ocamlprof -version | grep ${{ version }}

          echo "Testing ocamlopt..." && ocamlopt -version | grep ${{ version }}
          echo "Testing ocamldoc..." && ocamldoc -version | grep ${{ version }}
          echo "Testing ocamldoc.opt..." && ocamldoc.opt -version | grep ${{ version }}
          echo "Testing ocamldebug..." && ocamldebug -version | grep ${{ version }}
          echo "Testing ocamlobjinfo..." && ocamlobjinfo -help
          echo "Testing ocamlobjinfo.opt..." && ocamlobjinfo.opt -help
          echo "Testing ocamlcmt..." && ocamlcmt -help
          echo "Testing ocamlobjinfo.byte..." && ocamlobjinfo.byte -help
        requirements:
          run:
            - ${{ m2 }}grep
      - script:
          - echo "=== Exercise compilers with actual code ==="
          - printf 'print_endline "Hello World"\n' > hi.ml
          - if: unix
            then: |
                # 1. Bytecode compilation + execution
                echo "=== Testing bytecode compilation ==="
                ocamlc -o hi hi.ml && ./hi | grep "Hello World"
                (mkdir -p tmp && cp hi tmp && (cd tmp; ./hi)) | grep "Hello World" && rm ./hi
                ocamlrun ${PREFIX}/bin/ocamlc.byte -version | grep ${{ version }}

                # 2. Native compilation + execution
                echo "=== Testing native compilation ==="
                ocamlopt -o hi hi.ml && ./hi | grep "Hello World" && rm ./hi

                # 3. REPL test (ocaml toplevel)
                echo "=== Testing REPL ==="
                echo 'print_endline "REPL works";;' | ocaml 2>&1 || echo "REPL exit: $?"

                # 4. ocamldep actually parsing files
                echo "=== Testing ocamldep ==="
                ocamldep hi.ml
 
                # 5. Multi-file compilation (exercises module system)
                echo "=== Testing multi-file compilation ==="
                printf 'let greet () = print_endline "From Lib"\n' > lib.ml
                printf 'let () = Lib.greet ()\n' > main.ml
                ocamlc -c lib.ml
                ocamlc -c main.ml
                ocamlc -o multi lib.cmo main.cmo
                ./multi | grep "From Lib"

                echo "=== Bytecode compiler via ocamlrun ==="
                ocamlrun ${PREFIX}/bin/ocamlc.byte -version
                printf 'print_endline "Hi CF"\n' > hi.ml && ocamlrun ${PREFIX}/bin/ocamlc.byte -o hi hi.ml && ./hi && rm ./hi

                echo "=== All compilation tests passed ==="
            else:
              - ocamlc -o hi.exe hi.ml && hi.exe | grep Hello && rm hi.exe
        requirements:
          run:
            - ${{ c_compiler }}_impl_${{ target_platform }} >=${{ c_compiler_version }}
            - ${{ m2 }}file
            - ${{ m2 }}grep
            - if: osx
              then:
                - lld >=${{ c_compiler_version }}
                - llvm-tools >=${{ c_compiler_version }}
    about:
      summary: OCaml compilers for ${{ target_platform }}
      license: LGPL-2.1-only WITH OCaml-LGPL-linking-exception
      license_file: LICENSE

  # ============================================================================
  # Output 3: Cross-compiler (built on native platform, targets cross_target)
  # ============================================================================
  - package:
      name: ocaml-cross-compiler_${{ cross_target }}
    build:
      # Build only when:
      # 1. We're on the platform that builds this cross-compiler (build_platform == cross_build)
      # 2. This is a native build, not a cross-build job (build_platform == target_platform)
      skip: (build_platform != cross_build) or (build_platform != target_platform)
      script:
        content: |
          echo "Building ocaml-cross-compiler_${{ cross_target }}"
          source "${RECIPE_DIR}"/building/build-cross-compiler.sh
        env:
          CROSS_TARGET_PLATFORM: ${{ cross_target }}
          CROSS_HOST_ALIAS: ${{ triplet_target }}
      dynamic_linking:
        missing_dso_allowlist:
          - if: linux
            then:
              - ${{ cross_linker }}
      prefix_detection:
        force_file_type:
          text:
            - ocaml-cross-compilers/${{ triplet_target }}/lib/ocaml/ld.conf
            - ocaml-cross-compilers/${{ triplet_target }}/lib/ocaml/Makefile.config
            - ocaml-cross-compilers/${{ triplet_target }}/lib/ocaml/runtime-launch-info
        ignore:
          - ocaml-cross-compilers/${{ triplet_target }}/lib/ocaml/**/*.cmo
          - ocaml-cross-compilers/${{ triplet_target }}/lib/ocaml/**/*.cma
          - ocaml-cross-compilers/${{ triplet_target }}/lib/ocaml/**/*.cmi
          - ocaml-cross-compilers/${{ triplet_target }}/lib/ocaml/**/*.cmx
          - ocaml-cross-compilers/${{ triplet_target }}/lib/ocaml/**/*.cmt
          - ocaml-cross-compilers/${{ triplet_target }}/lib/ocaml/**/*.cmti
    requirements:
      build:
        - ${{ compiler('c') }}
        - ${{ stdlib('c') }}
        - ${{ c_compiler }}_impl_${{ cross_target }} ${{ c_compiler_version }}.*
        - if: linux
          then:
            - ${{ c_stdlib }}_${{ cross_target }} =${{ c_stdlib_version }}
          else:
            - ${{ c_stdlib }}_${{ cross_target }} =${{ amr64_sdk }}
        # Use regular dependency (not pin_subpackage) to allow resolution from channel
        # when the native OCaml is built on a different platform
        - ocaml_${{ cross_build }} ==${{ version }}
        - binutils_impl_${{ cross_target }}
        - bash >=5.2
        - make
        - pkgconfig
      host:
        - zstd
        - if: osx
          then:
            - lld ${{ c_compiler_version }}.*
            - llvm-tools ${{ c_compiler_version }}.*
    tests:
      - package_contents:
          bin:
            - ${{ triplet_target }}-ocamlc
            - ${{ triplet_target }}-ocamldep
            - ${{ triplet_target }}-ocamlobjinfo
            - ${{ triplet_target }}-ocamlopt
            - ocaml-cross-compilers/${{ triplet_target }}/lib/ocaml/libasmrun.a
            - ocaml-cross-compilers/${{ triplet_target }}/lib/ocaml/runtime-launch-info
            - ocaml-cross-compilers/${{ triplet_target }}/lib/ocaml/*.a
            - ocaml-cross-compilers/${{ triplet_target }}/lib/ocaml/*.cma
            - ocaml-cross-compilers/${{ triplet_target }}/lib/ocaml/*.cmi
            - ocaml-cross-compilers/${{ triplet_target }}/lib/ocaml/*.cmo
            - ocaml-cross-compilers/${{ triplet_target }}/lib/ocaml/*.cmx
            - ocaml-cross-compilers/${{ triplet_target }}/lib/ocaml/*.cmxa
            - ocaml-cross-compilers/${{ triplet_target }}/lib/ocaml/*.o
            - ocaml-cross-compilers/${{ triplet_target }}/lib/ocaml/stublibs/dll*.${{ so }}
      - script: |
            echo "Testing ${{ cross_target }} cross-compilers..."
            echo "  ocamlc..." && ${{ triplet_target }}-ocamlc -version | grep ${{ version }}
            echo "  ocamldep..." && ${{ triplet_target }}-ocamldep -version | grep ${{ version }}
            echo "  ocamlobjinfo..." && ${{ triplet_target }}-ocamlobjinfo -help | grep -q FILES
            echo "  ocamlopt..." && ${{ triplet_target }}-ocamlopt -version | grep ${{ version }}
        requirements:
          run:
            - grep
    about:
      summary: OCaml cross-compiler for ${{ cross_target }}
      license: LGPL-2.1-only WITH OCaml-LGPL-linking-exception
      license_file: LICENSE

about:
  homepage: https://ocaml.org/
  license: LGPL-2.1-only WITH OCaml-LGPL-linking-exception
  license_file: LICENSE
  summary: OCaml is an industrial strength programming language supporting functional, imperative and object-oriented styles
  description: |
    OCaml is a general purpose industrial-strength programming language with an
    emphasis on expressiveness and safety. Developed for more than 20 years at
    Inria it benefits from one of the most advanced type systems and supports
    functional, imperative and object-oriented styles of programming.

    The OCaml system is a comprehensive implementation of the Caml language,
    featuring two compilers:

    A bytecode compiler (ocamlc) producing small, portable, fast-starting
    bytecode executables suitable for day-to-day development and prototyping on
    32 or 64 bit Unix platform. Performance of generated programs is quite good
    for a bytecoded implementation.  This compiler can be used either as a
    standalone, batch-oriented compiler that produces standalone programs, or as
    an interactive, toplevel-based system.

    The other compiler generates high-performance native code for a number of
    processors. Compilation takes longer and generates bigger code, but the
    generated programs deliver excellent performance, while retaining the
    moderate memory requirements of the bytecode compiler.
  documentation: https://ocaml.org/docs/
  repository: https://github.com/ocaml/ocaml

extra:
  feedstock-name: ocaml
  recipe-maintainers:
    - isuruf
    - dslarm
    - MementoRC
