context:
  name: ocaml
  version: 5.3.0
  flexdll_version: 0.44
  m2: ${{ "m2-" if not unix }}

package:
  name: ocaml
  version: ${{ version }}

source:
  - url: https://github.com/ocaml/ocaml/archive/refs/tags/${{ version }}.tar.gz
    sha256: eb9eab2f21758d3cfb1e78c7f83f0b4dd6302824316aba4abee047a5a4f85029
  - if: win
    then:
      url: https://github.com/ocaml/flexdll/archive/refs/tags/${{ flexdll_version }}.tar.gz
      sha256: b7c6a92286f1f3065324d51083dcb16eec436a4e6e3b8df7cf836b6d7a8b9491
      target_directory: flexdll

build:
  number: 1
  script:
    env:
      SKIP_MAKE_TESTS: 1
  dynamic_linking:
    missing_dso_allowlist:
      - if: osx
        then:
          - /usr/lib/libSystem.B.dylib
      - if: not unix
        then:
          - C:\\Windows\\system32\\SHLWAPI.dll
          - C:\\Windows\\system32\\VERSION.dll
  prefix_detection:
    force_file_type:
      text:
        # These are actual text files that need prefix relocation
        - lib/ocaml/ld.conf
        - lib/ocaml/Makefile.config
        - lib/ocaml/runtime-launch-info
    ignore:
      # Only ignore bytecode files (binary format, relocation corrupts them)
      - lib/ocaml/**/*.cmo
      - lib/ocaml/**/*.cma
      - lib/ocaml/**/*.cmi
      - lib/ocaml/**/*.cmx
      - lib/ocaml/**/*.cmt
      - lib/ocaml/**/*.cmti
      # Bytecode executables - MUST ignore to avoid corrupting binary data
      # These use #!/usr/bin/env ocamlrun shebang which doesn't need relocation
      - bin/ocaml
      - bin/ocamlc.byte
      - bin/ocamlcmt
      - bin/ocamlcp
      - bin/ocamldebug
      - bin/ocamldoc
      - bin/ocamldep.byte
      - bin/ocamllex.byte
      - bin/ocamlmklib
      - bin/ocamlmktop
      - bin/ocamlobjinfo.byte
      - bin/ocamlopt.byte
      - bin/ocamloptp
      - bin/ocamlprof
      # These cause SEGV with QEMU when relocated (v5.3.0 only?)
      - bin/ocamlc
      - bin/ocamlopt

requirements:
  run_exports:
    - ${{ pin_subpackage("ocaml", upper_bound="x.x.x") }}
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    
    - ${{ m2 }}bash >=5.2
    - ${{ m2 }}file
    - ${{ m2 }}findutils
    - ${{ m2 }}gawk
    - ${{ m2 }}grep
    - ${{ m2 }}make
    - perl 5.32.*
    
    - if: not unix
      then:
        - binutils
        - ${{ m2 }}coreutils
        - ${{ m2 }}diffutils
        - ${{ m2 }}which
    - if: aarch64 or ppc64le or arm64
      then:
        - zstd
  host:
    - ${{ "m2-lib" if not unix }}zstd
  run:
    # OCaml runtime links against zstd for compressed marshaling
    - ${{ "m2-lib" if not unix }}zstd

tests:
  - package_contents:
      bin:
        - ocaml
        - ocamlc
        - ocamlc.byte
        - ocamlc.opt
        - ocamlcmt
        - ocamlcp
        - ocamldep
        - ocamldep.byte
        - ocamldep.opt
        - ocamllex
        - ocamllex.byte
        - ocamllex.opt
        - ocamlmklib
        - ocamlmktop
        - ocamlobjinfo
        - ocamlobjinfo.byte
        - ocamlobjinfo.opt
        - ocamlopt
        - ocamlopt.byte
        - ocamlopt.opt
        - ocamloptp
        - ocamlprof
        - ocamlrun
        - ocamlrund
        - ocamlyacc
        - if: build_platform == target_platform
          then:
            - ocamldebug
            - ocamldoc
            - ocamldoc.opt
        - if: unix
          then:
            - ocamlruni
          else:
            - flexlink
            - flexlink.byte
            - flexlink.opt

      files:
        - etc/conda/activate.d/ocaml_activate.${{ "sh" if unix else "bat" }}
        - etc/conda/deactivate.d/ocaml_deactivate.${{ "sh" if unix else "bat" }}
        - ${{ "Library/" if not unix }}lib/ocaml/**
        - ${{ "Library/" if not unix }}share/doc/ocaml/*
        - if: (build_platform == target_platform) and unix
          then: share/man/man{1,3}/*

  - script:
      - if: unix
        then: |
          echo "${OCAMLLIB:-'UNSET'}" | grep ocaml > /dev/null && { echo "OCAMLLIB set"; }
          head -2 ${PREFIX}/lib/ocaml/runtime-launch-info | grep ${PREFIX} > /dev/null && { echo "runtime-launch-info clean"; }
          head -2 ${PREFIX}/lib/ocaml/ld.conf | grep ${PREFIX} > /dev/null && { echo "ld.conf clean"; }
          cat ${PREFIX}/lib/ocaml/Makefile.config | grep ${PREFIX} > /dev/null && { echo "Makefile.config clean"; }
        else: |
          echo "%OCAMLLIB%" | grep ocaml
          echo "%PATH%" | grep ocaml
      - echo "PREFIX/PATH tests passed"
    requirements:
      run:
        - ${{ stdlib('c') }}
        - ${{ m2 }}grep

  - script:
      - if: build_platform != target_platform
        then:
          - if: aarch64
            then:
              - readelf -h ${PREFIX}/bin/ocamlc.opt | grep -q "AArch64" || { echo "Bad Arch"; exit 1; }
              - readelf -h ${PREFIX}/bin/ocamlrun | grep -q "AArch64" || { echo "Bad Arch"; exit 1; }
          - if: arm64
            then:
              - otool -hv ${PREFIX}/bin/ocamlc.opt # | grep -iq "ARM64" || { echo "Bad Arch"; exit 1; }
              - otool -hv ${PREFIX}/bin/ocamlrun # | grep -iq "ARM64" || { echo "Bad Arch"; exit 1; }
          - if: ppc64le
            then:
              - readelf -h ${PREFIX}/bin/ocamlc.opt | grep -q "PowerPC64" || { echo "Bad Arch"; exit 1; }
              - readelf -h ${PREFIX}/bin/ocamlrun | grep -q "PowerPC64" || { echo "Bad Arch"; exit 1; }
          - echo "Cross-compiled binary arch passed"
    requirements:
      run:
        - ${{ stdlib('c') }}

  - script:
      env:
        OCAMLRUNPARAM: "s=4M,o=1000"
      content:
        # === DIAGNOSTIC: All binaries version/info output ===
        - if: arm64
          then:
            - echo "Skipped test for ARM64"
          else: |
            ocamlc -version | grep ${{ version }}
            ocamldep -version | grep ${{ version }}
            ocamllex -version | grep ${{ version }}
            ocamlobjinfo -help | grep FILES
            ocamlobjinfo.opt -help | grep FILES
            ocamlrun -version | grep ${{ version }} || { ocamlrun -version; }
            ocamlyacc -version | grep ${{ version }} || { ocamlyacc -version; }

            # Bytecode sensitive to conda PREFIX detection
            ocaml -version | grep ${{ version }}
            ocamlcmt -help | grep FILE
            ocamlcp -version | grep ${{ version }}
            ocamlmklib -version | grep ${{ version }}
            ocamlmktop -version | grep ${{ version }}
            ocamlobjinfo.byte -help
            ocamloptp -version | grep ${{ version }}
            ocamlprof -version | grep ${{ version }}

            ocamlopt -version | grep ${{ version }}
        - if: build_platform == target_platform
          then: |
            ocamldoc -version | grep ${{ version }}
            ocamldoc.opt -version | grep ${{ version }}
            ocamldebug -version | grep ${{ version }}
      requirements:
        run:
          - ${{ stdlib('c') }}
          - ${{ m2 }}grep

  - script:
      env:
        OCAMLRUNPARAM: "s=4M,o=1000"
      content:
        - if: arm64
          then:
            - echo "Skipped test for ARM64"
          else:
            - printf 'print_endline "Hello World"\n' > hi.ml
            - if: unix
              then:
                - |
                  # 1. Bytecode compilation + execution
                  echo "=== Testing bytecode compilation ==="
                  ocamlc -o hi hi.ml && ./hi | grep "Hello World"
                  (mkdir -p tmp && cp hi tmp && (cd tmp; ./hi)) | grep "Hello World" && rm ./hi
                  ocamlrun ${PREFIX}/bin/ocamlc.byte -version | grep ${{ version }}

                  # 2. Native compilation + execution
                  echo "=== Testing native compilation ==="
                  ocamlopt -o hi hi.ml && ./hi | grep "Hello World" && rm ./hi

                  # 3. REPL test (ocaml toplevel)
                  echo "=== Testing REPL ==="
                  echo 'print_endline "REPL works";;' | ocaml 2>&1 || echo "REPL exit: $?"

                  # 4. ocamldep actually parsing files
                  echo "=== Testing ocamldep ==="
                  ocamldep hi.ml
 
                  # 5. Multi-file compilation (exercises module system)
                  echo "=== Testing multi-file compilation ==="
                  printf 'let greet () = print_endline "From Lib"\n' > lib.ml
                  printf 'let () = Lib.greet ()\n' > main.ml
                  ocamlc -c lib.ml
                  ocamlc -c main.ml
                  ocamlc -o multi lib.cmo main.cmo
                  ./multi | grep "From Lib"

                  echo "=== Bytecode compiler via ocamlrun ==="
                  ocamlrun ${PREFIX}/bin/ocamlc.byte -version
                  printf 'print_endline "Hi CF"\n' > hi.ml && ocamlrun ${PREFIX}/bin/ocamlc.byte -o hi hi.ml && ./hi && rm ./hi

                  echo "=== All compilation tests passed ==="
              else:
                - ocamlc -o hi.exe hi.ml && hi.exe | grep Hello && rm hi.exe
      requirements:
        run:
          - ${{ compiler('c') }}
          - ${{ stdlib('c') }}
          - ${{ m2 }}file
          - ${{ m2 }}grep

about:
  homepage: https://ocaml.org/
  license: LGPL-2.1-only WITH OCaml-LGPL-linking-exception
  license_family: LGPL
  license_file: LICENSE
  summary: Objective Caml (OCaml) is an implementation of the ML language.
  description: |
    OCaml is an implementation of the ML language, based on the Caml Light
    dialect extended with a complete class-based object system and a powerful
    module system in the style of Standard ML.

    OCaml comprises two compilers. One generates bytecode which is then
    interpreted by a C program. This compiler runs quickly, generates compact
    code with moderate memory requirements, and is portable to essentially any
    32 or 64 bit Unix platform. Performance of generated programs is quite good
    for a bytecoded implementation.  This compiler can be used either as a
    standalone, batch-oriented compiler that produces standalone programs, or as
    an interactive, toplevel-based system.

    The other compiler generates high-performance native code for a number of
    processors. Compilation takes longer and generates bigger code, but the
    generated programs deliver excellent performance, while retaining the
    moderate memory requirements of the bytecode compiler.
  documentation: https://ocaml.org/docs/
  repository: https://github.com/ocaml/ocaml

extra:
  recipe-maintainers:
    - isuruf
    - dslarm
    - MementoRC
