appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Gswx+VyHhr1BRBd0fqxMDx3tEcAJf/WRaYr5NXZjjyUvR8fvxrnO4gJKpyymRAijeJ68arPO3N2eJJZt8C3fUb4nP895w+jNZZkIY5B602JoVahjbwYm78D5eq6/AO5PDa6ouCp5VzN44xnIkjmGMZ18NwzFUAm6p3B6An0tz7GOVEXQaN9CsmDVibFKd7Vybbf9YyMuHK8Qglx3wbbFdi1/tsvu38ug1n4rcQbwM1fpNA/8T0s8uQUpbjytuvn9pJZ/t2Mh8rbaIr4lZVQrQbRFs6mi+LZYYxWWDj/7DdQcGsh1WxSJPEgkgQUi56fqLYWqPn2MJvz2YmD/YLRFLKcyZmcc4X7K3RKx3KrNQeQ9Yeo//f78bZgr+CQZUUsYlgKBlKABRf+nKlA9brOOGc8CabOq8BuVAz8EnqnwtbUw9XwJvYIk/ZZwcezukIDXMEuO2Umsr4/8WfbuyC931SI6z3dCyOt3Q3rAc0r7F7nVTsA9sm2voifJ/U3rwJvV+3oQFyG6pmdHKf0jRnB3QfdOb4gOzXW5DuXX5bk7uocUosYien+QXDiDXmp3salDt+z2gfnz+8FFCpwswr42oE7l2sRVr3l8V/jNG7OTp9QIMojH8H3t35Ye89YXQRlj5eR9o8QHaSJ5WdKCpLV1FeYdOh/wS03BVV/njR6yoy8=}
