# -*- mode: toml -*-
# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
"$schema" = "https://pixi.sh/v0.59.0/schema/manifest/schema.json"

[workspace]
name = "ocaml-feedstock-5.4.0-altc-feedstock"
version = "2026.8.9"  # conda-smithy version used to generate this file
description = "Pixi configuration for conda-forge/ocaml-feedstock-5.4.0-altc-feedstock"
authors = ["@conda-forge/ocaml-feedstock-5.4.0-altc"]
channels = ["conda-forge"]
platforms = ["linux-64", "linux-aarch64", "osx-64", "osx-arm64", "win-64"]
requires-pixi = ">=0.59.0"

[tasks.build-locally]
cmd = "pixi exec --force-reinstall --list='^python$' python ./build-locally.py"
description = "Build packages locally using the same setup scripts used in conda-forge's CI"
[tasks.smithy]
cmd = "pixi exec --force-reinstall --list='^conda-smithy$' conda-smithy"
description = "Run conda-smithy. Pass necessary arguments."
[tasks.rerender]
cmd = "pixi exec --force-reinstall --list='^conda-smithy$' conda-smithy rerender"
description = "Rerender the feedstock."

[tasks.lint]
cmd = "pixi exec --list='^conda-smithy$' conda-smithy lint --conda-forge recipe"
description = "Lint the feedstock recipe"

[feature.build.dependencies]
conda-build = ">=26.3"
conda-forge-ci-setup = "4.*"
rattler-build = "*"

[feature.build.tasks.inspect-all]
cmd = "inspect_artifacts --all-packages"
description = "List contents of all packages found in rattler-build build directory."
[feature.build.tasks.build]
cmd = "rattler-build build --recipe recipe"
description = "Build ocaml-feedstock-5.4.0-altc-feedstock directly (without setup scripts), no particular variant specified"
[feature.build.tasks."build-linux_64_cross_target_platform_linux-64"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_64_cross_target_platform_linux-64.yaml"
description = "Build ocaml-feedstock-5.4.0-altc-feedstock with variant linux_64_cross_target_platform_linux-64 directly (without setup scripts)"
[feature.build.tasks."debug-linux_64_cross_target_platform_linux-64"]
cmd = "rattler-build debug setup --recipe recipe -m .ci_support/linux_64_cross_target_platform_linux-64.yaml"
description = "Build ocaml-feedstock-5.4.0-altc-feedstock with variant linux_64_cross_target_platform_linux-64 directly (without setup scripts)"
[feature.build.tasks."inspect-linux_64_cross_target_platform_linux-64"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_cross_target_platform_linux-64.yaml"
description = "List contents of ocaml-feedstock-5.4.0-altc-feedstock packages built for variant linux_64_cross_target_platform_linux-64"
[feature.build.tasks."build-linux_64_cross_target_platform_linux-ppc64le"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_64_cross_target_platform_linux-ppc64le.yaml"
description = "Build ocaml-feedstock-5.4.0-altc-feedstock with variant linux_64_cross_target_platform_linux-ppc64le directly (without setup scripts)"
[feature.build.tasks."debug-linux_64_cross_target_platform_linux-ppc64le"]
cmd = "rattler-build debug setup --recipe recipe -m .ci_support/linux_64_cross_target_platform_linux-ppc64le.yaml"
description = "Build ocaml-feedstock-5.4.0-altc-feedstock with variant linux_64_cross_target_platform_linux-ppc64le directly (without setup scripts)"
[feature.build.tasks."inspect-linux_64_cross_target_platform_linux-ppc64le"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_cross_target_platform_linux-ppc64le.yaml"
description = "List contents of ocaml-feedstock-5.4.0-altc-feedstock packages built for variant linux_64_cross_target_platform_linux-ppc64le"
[feature.build.tasks."build-linux_64_cross_target_platform_linux-riscv64"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_64_cross_target_platform_linux-riscv64.yaml"
description = "Build ocaml-feedstock-5.4.0-altc-feedstock with variant linux_64_cross_target_platform_linux-riscv64 directly (without setup scripts)"
[feature.build.tasks."debug-linux_64_cross_target_platform_linux-riscv64"]
cmd = "rattler-build debug setup --recipe recipe -m .ci_support/linux_64_cross_target_platform_linux-riscv64.yaml"
description = "Build ocaml-feedstock-5.4.0-altc-feedstock with variant linux_64_cross_target_platform_linux-riscv64 directly (without setup scripts)"
[feature.build.tasks."inspect-linux_64_cross_target_platform_linux-riscv64"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_cross_target_platform_linux-riscv64.yaml"
description = "List contents of ocaml-feedstock-5.4.0-altc-feedstock packages built for variant linux_64_cross_target_platform_linux-riscv64"
[feature.build.tasks."build-linux_64_cross_target_platform_linux-s390x"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_64_cross_target_platform_linux-s390x.yaml"
description = "Build ocaml-feedstock-5.4.0-altc-feedstock with variant linux_64_cross_target_platform_linux-s390x directly (without setup scripts)"
[feature.build.tasks."debug-linux_64_cross_target_platform_linux-s390x"]
cmd = "rattler-build debug setup --recipe recipe -m .ci_support/linux_64_cross_target_platform_linux-s390x.yaml"
description = "Build ocaml-feedstock-5.4.0-altc-feedstock with variant linux_64_cross_target_platform_linux-s390x directly (without setup scripts)"
[feature.build.tasks."inspect-linux_64_cross_target_platform_linux-s390x"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_cross_target_platform_linux-s390x.yaml"
description = "List contents of ocaml-feedstock-5.4.0-altc-feedstock packages built for variant linux_64_cross_target_platform_linux-s390x"
[feature.build.tasks."build-linux_aarch64_cross_target_platform_linux-aarch64"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_aarch64_cross_target_platform_linux-aarch64.yaml"
description = "Build ocaml-feedstock-5.4.0-altc-feedstock with variant linux_aarch64_cross_target_platform_linux-aarch64 directly (without setup scripts)"
[feature.build.tasks."debug-linux_aarch64_cross_target_platform_linux-aarch64"]
cmd = "rattler-build debug setup --recipe recipe -m .ci_support/linux_aarch64_cross_target_platform_linux-aarch64.yaml"
description = "Build ocaml-feedstock-5.4.0-altc-feedstock with variant linux_aarch64_cross_target_platform_linux-aarch64 directly (without setup scripts)"
[feature.build.tasks."inspect-linux_aarch64_cross_target_platform_linux-aarch64"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_aarch64_cross_target_platform_linux-aarch64.yaml"
description = "List contents of ocaml-feedstock-5.4.0-altc-feedstock packages built for variant linux_aarch64_cross_target_platform_linux-aarch64"
[feature.build.tasks."build-linux_ppc64le_cross_target_platform_linux-ppc64le"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_ppc64le_cross_target_platform_linux-ppc64le.yaml"
description = "Build ocaml-feedstock-5.4.0-altc-feedstock with variant linux_ppc64le_cross_target_platform_linux-ppc64le directly (without setup scripts)"
[feature.build.tasks."debug-linux_ppc64le_cross_target_platform_linux-ppc64le"]
cmd = "rattler-build debug setup --recipe recipe -m .ci_support/linux_ppc64le_cross_target_platform_linux-ppc64le.yaml"
description = "Build ocaml-feedstock-5.4.0-altc-feedstock with variant linux_ppc64le_cross_target_platform_linux-ppc64le directly (without setup scripts)"
[feature.build.tasks."inspect-linux_ppc64le_cross_target_platform_linux-ppc64le"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_ppc64le_cross_target_platform_linux-ppc64le.yaml"
description = "List contents of ocaml-feedstock-5.4.0-altc-feedstock packages built for variant linux_ppc64le_cross_target_platform_linux-ppc64le"
[feature.build.tasks."build-linux_riscv64_cross_target_platform_linux-riscv64"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_riscv64_cross_target_platform_linux-riscv64.yaml"
description = "Build ocaml-feedstock-5.4.0-altc-feedstock with variant linux_riscv64_cross_target_platform_linux-riscv64 directly (without setup scripts)"
[feature.build.tasks."debug-linux_riscv64_cross_target_platform_linux-riscv64"]
cmd = "rattler-build debug setup --recipe recipe -m .ci_support/linux_riscv64_cross_target_platform_linux-riscv64.yaml"
description = "Build ocaml-feedstock-5.4.0-altc-feedstock with variant linux_riscv64_cross_target_platform_linux-riscv64 directly (without setup scripts)"
[feature.build.tasks."inspect-linux_riscv64_cross_target_platform_linux-riscv64"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_riscv64_cross_target_platform_linux-riscv64.yaml"
description = "List contents of ocaml-feedstock-5.4.0-altc-feedstock packages built for variant linux_riscv64_cross_target_platform_linux-riscv64"
[feature.build.tasks."build-linux_s390x_cross_target_platform_linux-s390x"]
cmd = "rattler-build build --recipe recipe -m .ci_support/linux_s390x_cross_target_platform_linux-s390x.yaml"
description = "Build ocaml-feedstock-5.4.0-altc-feedstock with variant linux_s390x_cross_target_platform_linux-s390x directly (without setup scripts)"
[feature.build.tasks."debug-linux_s390x_cross_target_platform_linux-s390x"]
cmd = "rattler-build debug setup --recipe recipe -m .ci_support/linux_s390x_cross_target_platform_linux-s390x.yaml"
description = "Build ocaml-feedstock-5.4.0-altc-feedstock with variant linux_s390x_cross_target_platform_linux-s390x directly (without setup scripts)"
[feature.build.tasks."inspect-linux_s390x_cross_target_platform_linux-s390x"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_s390x_cross_target_platform_linux-s390x.yaml"
description = "List contents of ocaml-feedstock-5.4.0-altc-feedstock packages built for variant linux_s390x_cross_target_platform_linux-s390x"
[feature.build.tasks."build-osx_64_cross_target_platform_osx-64"]
cmd = "rattler-build build --recipe recipe -m .ci_support/osx_64_cross_target_platform_osx-64.yaml"
description = "Build ocaml-feedstock-5.4.0-altc-feedstock with variant osx_64_cross_target_platform_osx-64 directly (without setup scripts)"
[feature.build.tasks."debug-osx_64_cross_target_platform_osx-64"]
cmd = "rattler-build debug setup --recipe recipe -m .ci_support/osx_64_cross_target_platform_osx-64.yaml"
description = "Build ocaml-feedstock-5.4.0-altc-feedstock with variant osx_64_cross_target_platform_osx-64 directly (without setup scripts)"
[feature.build.tasks."inspect-osx_64_cross_target_platform_osx-64"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/osx_64_cross_target_platform_osx-64.yaml"
description = "List contents of ocaml-feedstock-5.4.0-altc-feedstock packages built for variant osx_64_cross_target_platform_osx-64"
[feature.build.tasks."build-osx_arm64_cross_target_platform_osx-arm64"]
cmd = "rattler-build build --recipe recipe -m .ci_support/osx_arm64_cross_target_platform_osx-arm64.yaml"
description = "Build ocaml-feedstock-5.4.0-altc-feedstock with variant osx_arm64_cross_target_platform_osx-arm64 directly (without setup scripts)"
[feature.build.tasks."debug-osx_arm64_cross_target_platform_osx-arm64"]
cmd = "rattler-build debug setup --recipe recipe -m .ci_support/osx_arm64_cross_target_platform_osx-arm64.yaml"
description = "Build ocaml-feedstock-5.4.0-altc-feedstock with variant osx_arm64_cross_target_platform_osx-arm64 directly (without setup scripts)"
[feature.build.tasks."inspect-osx_arm64_cross_target_platform_osx-arm64"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/osx_arm64_cross_target_platform_osx-arm64.yaml"
description = "List contents of ocaml-feedstock-5.4.0-altc-feedstock packages built for variant osx_arm64_cross_target_platform_osx-arm64"
[feature.build.tasks."build-win_64_c_compilergcccross_target_platform_win-64"]
cmd = "rattler-build build --recipe recipe -m .ci_support/win_64_c_compilergcccross_target_platform_win-64.yaml"
description = "Build ocaml-feedstock-5.4.0-altc-feedstock with variant win_64_c_compilergcccross_target_platform_win-64 directly (without setup scripts)"
[feature.build.tasks."debug-win_64_c_compilergcccross_target_platform_win-64"]
cmd = "rattler-build debug setup --recipe recipe -m .ci_support/win_64_c_compilergcccross_target_platform_win-64.yaml"
description = "Build ocaml-feedstock-5.4.0-altc-feedstock with variant win_64_c_compilergcccross_target_platform_win-64 directly (without setup scripts)"
[feature.build.tasks."inspect-win_64_c_compilergcccross_target_platform_win-64"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/win_64_c_compilergcccross_target_platform_win-64.yaml"
description = "List contents of ocaml-feedstock-5.4.0-altc-feedstock packages built for variant win_64_c_compilergcccross_target_platform_win-64"
[feature.build.tasks."build-win_64_c_compilervs2022cross_target_platform_win-64"]
cmd = "rattler-build build --recipe recipe -m .ci_support/win_64_c_compilervs2022cross_target_platform_win-64.yaml"
description = "Build ocaml-feedstock-5.4.0-altc-feedstock with variant win_64_c_compilervs2022cross_target_platform_win-64 directly (without setup scripts)"
[feature.build.tasks."debug-win_64_c_compilervs2022cross_target_platform_win-64"]
cmd = "rattler-build debug setup --recipe recipe -m .ci_support/win_64_c_compilervs2022cross_target_platform_win-64.yaml"
description = "Build ocaml-feedstock-5.4.0-altc-feedstock with variant win_64_c_compilervs2022cross_target_platform_win-64 directly (without setup scripts)"
[feature.build.tasks."inspect-win_64_c_compilervs2022cross_target_platform_win-64"]
cmd = "inspect_artifacts --recipe-dir recipe -m .ci_support/win_64_c_compilervs2022cross_target_platform_win-64.yaml"
description = "List contents of ocaml-feedstock-5.4.0-altc-feedstock packages built for variant win_64_c_compilervs2022cross_target_platform_win-64"

[environments]
build = ["build"]
# This is a copy of 'build', to be enabled by build_steps.sh during Docker builds
# __PLATFORM_SPECIFIC_ENV__ = ["build"]
