# ============================================================================
# CROSS-COMPILERS BUILD SCRIPT
# Builds cross-compilers for aarch64/ppc64le (on linux-64) or arm64 (on osx-64)
#
# Variables:
#   OCAML_PREFIX         - Where native OCaml is installed (source for native tools)
#   OCAML_INSTALL_PREFIX - Where cross-compilers will be installed (destination)
# ============================================================================

# Source common functions
source "${RECIPE_DIR}/building/common-functions.sh"

if [[ "${target_platform}" != "linux"* ]] && [[ "${target_platform}" != "osx"* ]]; then
  echo "No cross-compiler recipe for ${target_platform} ... yet"
  return 0
fi

# ============================================================================
# Configuration
# ============================================================================

# OCAML_PREFIX = where native OCaml is installed (source for native tools)
# OCAML_INSTALL_PREFIX = where cross-compilers will be installed (destination)
: "${OCAML_PREFIX:=${PREFIX}}"
: "${OCAML_INSTALL_PREFIX:=${PREFIX}}"

# macOS: Set DYLD_LIBRARY_PATH so native compiler can find libzstd at runtime
# The native compiler (x86_64) needs BUILD_PREFIX libs, not PREFIX (which has target arch libs)
# Cross-compilation: PREFIX=ARM64, BUILD_PREFIX=x86_64
# Native build: PREFIX=x86_64, BUILD_PREFIX=x86_64 (same)
if [[ "${target_platform}" == "osx"* ]]; then
  if [[ "${CONDA_BUILD_CROSS_COMPILATION:-0}" == "1" ]]; then
    export DYLD_LIBRARY_PATH="${BUILD_PREFIX}/lib:${DYLD_LIBRARY_PATH:-}"
    export LIBRARY_PATH="${BUILD_PREFIX}/lib:${LIBRARY_PATH:-}"
  else
    export DYLD_LIBRARY_PATH="${PREFIX}/lib:${DYLD_LIBRARY_PATH:-}"
    export LIBRARY_PATH="${PREFIX}/lib:${LIBRARY_PATH:-}"
  fi
fi

# Define cross targets based on build platform
CONFIG_ARGS+=(--with-target-bindir="${PREFIX}"/bin)
declare -a CROSS_TARGETS
case "${target_platform}" in
  linux-64)
    CROSS_TARGETS=("aarch64-conda-linux-gnu" "powerpc64le-conda-linux-gnu")
    CONFIG_ARGS+=(--enable-frame-pointers)
    ;;
  linux-aarch64)
    CROSS_TARGETS=("aarch64-conda-linux-gnu")
    CONFIG_ARGS+=(--enable-frame-pointers)
    ;;
  linux-ppc64le)
    CROSS_TARGETS=("powerpc64le-conda-linux-gnu")
    CONFIG_ARGS+=(--enable-frame-pointers)
    ;;
  osx-*)
    CROSS_TARGETS=("arm64-apple-darwin20.0.0")
    ;;
esac

# ============================================================================
# Build loop
# ============================================================================

echo ""
echo "============================================================"
echo "Cross-compiler build configuration"
echo "============================================================"
echo "  Native OCaml (source):    ${OCAML_PREFIX}"
echo "  Cross install (dest):     ${OCAML_INSTALL_PREFIX}"
echo "  Native ocamlopt:          ${OCAML_PREFIX}/bin/ocamlopt"

for target in "${CROSS_TARGETS[@]}"; do
  echo ""
  echo "  ------------------------------------------------------------"
  echo "  Building cross-compiler for ${target}"
  echo "  ------------------------------------------------------------"

  # Get target properties using common functions
  CROSS_ARCH=$(get_target_arch "${target}")
  CROSS_PLATFORM=$(get_target_platform "${target}")

  # Handle PowerPC model override
  CROSS_MODEL=""
  [[ "${target}" == "powerpc64le-"* ]] && CROSS_MODEL="ppc64le"

  # Setup macOS ARM64 SDK (must be done before setup_cflags_ldflags)
  if [[ "${target}" == "arm64-apple-darwin"* ]]; then
    echo "  Setting up macOS ARM64 SDK for cross-compilation..."
    setup_macos_sysroot "${target}"
    # CRITICAL: Override BOTH SDKROOT and CONDA_BUILD_SYSROOT
    # conda-forge sets CONDA_BUILD_SYSROOT=/opt/conda-sdks/MacOSX10.13.sdk for x86_64
    # The cross-compiler clang respects CONDA_BUILD_SYSROOT for library lookup
    # Without overriding it, lld finds the wrong SDK even with -syslibroot flags
    export SDKROOT="${ARM64_SYSROOT}"
    export CONDA_BUILD_SYSROOT="${ARM64_SYSROOT}"
    echo "  SDKROOT exported: ${SDKROOT}"
    echo "  CONDA_BUILD_SYSROOT exported: ${CONDA_BUILD_SYSROOT}"
  fi

  # Setup cross-toolchain (sets CROSS_CC, CROSS_AS, CROSS_AR, etc.)
  setup_toolchain "CROSS" "${target}"
  setup_cflags_ldflags "CROSS" "${build_platform}" "${CROSS_PLATFORM}"

  # Export CONDA_OCAML_<TARGET_ID>_* variables
  TARGET_ID=$(get_target_id "${target}")

  echo "  Target:        ${target}"
  echo "  Target ID:     ${TARGET_ID}"
  echo "  Arch:          ${CROSS_ARCH}"
  echo "  Platform:      ${CROSS_PLATFORM}"
  echo "  CROSS_AR:      ${CROSS_AR}"
  echo "  CROSS_AS:      ${CROSS_AS}"
  echo "  CROSS_ASM:     ${CROSS_ASM}"
  echo "  CROSS_CC:      ${CROSS_CC}"
  echo "  CROSS_CFLAGS:  ${CROSS_CFLAGS}"
  echo "  CROSS_LD:      ${CROSS_LD}"
  echo "  CROSS_LDFLAGS: ${CROSS_LDFLAGS}"
  echo "  CROSS_RANLIB:  ${CROSS_RANLIB}"

  cat > "${SRC_DIR}/_xcross_compiler_${target_platform}_env.sh" << EOF
# Generated by build-cross-compiler.sh - do not edit
export "CROSS_AR=${CROSS_AR}"
export "CROSS_AS=${CROSS_AS}"
export "CROSS_ASM=${CROSS_ASM}"
export "CROSS_CC=${CROSS_CC}"
export "CROSS_CFLAGS=${CROSS_CFLAGS}"
export "CROSS_LD=${CROSS_LD}"
export "CROSS_LDFLAGS=${CROSS_LDFLAGS}"
export "CROSS_RANLIB=${CROSS_RANLIB}"
export "CROSS_MKDLL=${CROSS_MKDLL}"
export "CROSS_MKEXE=${CROSS_MKEXE}"

# CONDA_OCAML_* for runtime (use CROSS_* not CONDA_OCAML_* which may be native)
export "CONDA_OCAML_${TARGET_ID}_AR=${CROSS_AR}"
export "CONDA_OCAML_${TARGET_ID}_AS=${CROSS_ASM}"
export "CONDA_OCAML_${TARGET_ID}_CC=${CROSS_CC}"
export "CONDA_OCAML_${TARGET_ID}_RANLIB=${CROSS_RANLIB}"
export "CONDA_OCAML_${TARGET_ID}_MKDLL=${CROSS_MKDLL}"
export "CONDA_OCAML_${TARGET_ID}_MKEXE=${CROSS_MKEXE}"
EOF

  # Installation prefix for this cross-compiler
  OCAML_CROSS_PREFIX="${OCAML_INSTALL_PREFIX}/lib/ocaml-cross-compilers/${target}"
  OCAML_CROSS_LIBDIR="${OCAML_CROSS_PREFIX}/lib/ocaml"
  mkdir -p "${OCAML_CROSS_PREFIX}/bin" "${OCAML_CROSS_LIBDIR}"

  # ========================================================================
  # Clean and configure
  # ========================================================================

  echo "  [1/5] Cleaning previous build..."
  run_logged "pre-cross-distclean" "${MAKE[@]}" distclean > /dev/null 2>&1 || true

  echo "  [2/5] Configuring for ${target}..."
  # PKG_CONFIG=false forces simple "-lzstd" instead of "-L/long/path -lzstd"
  # Do NOT pass CC here - configure needs BUILD compiler
  # ac_cv_func_getentropy=no: conda-forge uses glibc 2.17 sysroot which lacks getentropy
  # CRITICAL: Override CFLAGS/LDFLAGS - conda-build sets them for TARGET (ppc64le)
  # but configure needs BUILD flags (x86_64) to compile the cross-compiler binary
  run_logged "cross-configure" ${CONFIGURE[@]} \
    -prefix="${OCAML_CROSS_PREFIX}" \
    --host="${build_alias}" \
    --target="${target}" \
    --enable-frame-pointers \
    "${CONFIG_ARGS[@]}" \
    AR="${CROSS_AR}" \
    AS="${NATIVE_AS}" \
    CC="${NATIVE_CC}" \
    CFLAGS="${NATIVE_CFLAGS}" \
    LD="${NATIVE_LD}" \
    LDFLAGS="${NATIVE_LDFLAGS}" \
    NM="${CROSS_NM}" \
    RANLIB="${CROSS_RANLIB}" \
    STRIP="${CROSS_STRIP}" \
    ac_cv_func_getentropy=no \
    ${CROSS_MODEL:+MODEL=${CROSS_MODEL}}

  # ========================================================================
  # Patch config.generated.ml
  # ========================================================================

  echo "  [3/5] Patching config.generated.ml..."
  config_file="utils/config.generated.ml"

  # Use conda-ocaml-* wrapper scripts instead of $CONDA_OCAML_* variable references
  # Wrappers expand env vars at runtime, compatible with Unix.create_process
  sed -i \
    -e 's#^let asm = .*#let asm = {|conda-ocaml-as|}#' \
    -e 's#^let ar = .*#let ar = {|conda-ocaml-ar|}#' \
    -e 's#^let c_compiler = .*#let c_compiler = {|conda-ocaml-cc|}#' \
    -e 's#^let ranlib = .*#let ranlib = {|conda-ocaml-ranlib|}#' \
    -e 's#^let mkexe = .*#let mkexe = {|conda-ocaml-mkexe|}#' \
    -e 's#^let mkdll = .*#let mkdll = {|conda-ocaml-mkdll|}#' \
    -e 's#^let mkmaindll = .*#let mkmaindll = {|conda-ocaml-mkdll|}#' \
    "$config_file"
  # CRITICAL: Use the actual PREFIX path that conda will install to
  # OCAML_CROSS_LIBDIR may point to work/_xcross_compiler/... during build
  # We need to use ${PREFIX} (the conda prefix) which will be correct after install
  # Conda/rattler-build will relocate these paths during packaging
  FINAL_STDLIB_PATH="${PREFIX}/lib/ocaml-cross-compilers/${target}/lib/ocaml"
  sed -i "s#^let standard_library_default = .*#let standard_library_default = {|${FINAL_STDLIB_PATH}|}#" "$config_file"

  # CRITICAL: Patch architecture - this is baked into the binary!
  # CROSS_ARCH is set by get_target_arch() - values: arm64, power, amd64
  sed -i "s#^let architecture = .*#let architecture = {|${CROSS_ARCH}|}#" "$config_file"

  # Patch model for PowerPC
  [[ -n "${CROSS_MODEL}" ]] && sed -i "s#^let model = .*#let model = {|${CROSS_MODEL}|}#" "$config_file"

  # Patch native_pack_linker to use cross-linker via wrapper
  sed -i "s#^let native_pack_linker = .*#let native_pack_linker = {|conda-ocaml-ld -r -o |}#" "$config_file"

  echo "    Patched architecture=${CROSS_ARCH}"
  [[ -n "${CROSS_MODEL}" ]] && echo "    Patched model=${CROSS_MODEL}"
  echo "    Patched native_pack_linker=conda-ocaml-ld -r -o"

  # Apply Makefile.cross patches (includes otherlibrariesopt → otherlibrariesopt-cross fix)
  apply_cross_patches

  # ========================================================================
  # Pre-build bytecode runtime with NATIVE tools
  # ========================================================================
  # runtime-all builds BOTH bytecode (libcamlrun*, ocamlrun*) and native (libasmrun*).
  # Bytecode runs on BUILD machine → NATIVE tools; Native is for TARGET → CROSS tools.
  #
  # Strategy (prevents Stdlib__Sys consistency errors - see HISTORY.md):
  # 1. Build runtime-all with NATIVE tools (ARCH=amd64) - stable .cmi files
  # 2. Clean only native runtime files (libasmrun*, amd64.o, *.nd.o)
  # 3. crossopt rebuilds native parts for TARGET (bytecode unchanged)

  echo "  [4/6] Pre-building bytecode runtime and stdlib with native tools..."
  run_logged "runtime-all" "${MAKE[@]}" runtime-all \
    ARCH=amd64 \
    CC="${NATIVE_CC}" \
    CFLAGS="${NATIVE_CFLAGS}" \
    LD="${NATIVE_LD}" \
    LDFLAGS="${NATIVE_LDFLAGS}" \
    SAK_CC="${NATIVE_CC}" \
    SAK_CFLAGS="${NATIVE_CFLAGS}" \
    SAK_LDFLAGS="${NATIVE_LDFLAGS}" \
    ZSTD_LIBS="-L${BUILD_PREFIX}/lib -lzstd" \
    -j"${CPU_COUNT}" || { cat "${LOG_DIR}"/runtime-all.log; exit 1; }

  # NOTE: stdlib pre-build removed - was causing inconsistent assumptions
  # Let crossopt handle stdlib build entirely with consistent variables

  # Clean native runtime files so crossopt rebuilds them for TARGET arch
  # - libasmrun*.a: native runtime static libraries
  # - libasmrun_shared.so: native runtime shared library
  # - amd64*.o: x86_64 assembly objects (crossopt needs arm64*.o)
  # - *.nd.o, *.ni.o, *.npic.o: native code object files (need CROSS CC)
  # - stdlib/*.cmi: bytecode interface files (have ARCH-specific metadata)
  echo "     Cleaning native runtime and stdlib for crossopt rebuild..."
  rm -f runtime/libasmrun*.a runtime/libasmrun_shared.so
  rm -f runtime/amd64*.o runtime/*.nd.o runtime/*.ni.o runtime/*.npic.o
  rm -f runtime/libcomprmarsh.a  # Also needs CROSS tools

  # CRITICAL: Clean stdlib .cmi files - they contain arch-specific metadata
  # The .cmi files from runtime-all were built with ARCH=amd64, but crossopt
  # needs ARCH=arm64. Must force complete rebuild for consistency.
  # This prevents "inconsistent assumptions over implementation Stdlib__Sys" errors
  # between stdlib.cmxa and unix.cmxa (different CRC checksums).
  echo "     Cleaning stdlib compiled files to prevent arch inconsistencies..."
  rm -f stdlib/*.cmi stdlib/*.cmo stdlib/*.cma
  rm -f stdlib/*.cmx stdlib/*.cmxa stdlib/*.o stdlib/*.a

  # ========================================================================
  # Build cross-compiler
  # ========================================================================

  echo "  [5/6] Building cross-compiler (crossopt)..."

  (
    # Export CONDA_OCAML_* for cross-compilation (conda-ocaml-* wrappers expand these)
    # - Use CROSS_ASM (includes "-c" for macOS clang) not CROSS_AS
    # - MKEXE stays NATIVE (links x86_64 cross-compiler binary)
    # - OCAMLLIB will be set by Makefile.cross based on LIBDIR
    export CONDA_OCAML_AS="${CROSS_ASM}"
    export CONDA_OCAML_CC="${CROSS_CC}"
    export CONDA_OCAML_AR="${CROSS_AR}"
    export CONDA_OCAML_RANLIB="${CROSS_RANLIB}"
    export CONDA_OCAML_MKDLL="${CROSS_MKDLL}"

    # Ensure cross-tools are findable in PATH
    PATH="${OCAML_PREFIX}/bin:${PATH}"
    hash -r

    # Native compiler stdlib location (for copying fresh .cmi files in crossopt)
    NATIVE_STDLIB="${OCAML_PREFIX}/lib/ocaml"

    # Build arguments
    CROSSOPT_ARGS=(
      ARCH="${CROSS_ARCH}"
      AR="${CROSS_AR}"
      AS="${CROSS_AS}"
      ASPP="${CROSS_CC} -c"
      CAMLOPT=ocamlopt
      CC="${CROSS_CC}"
      CFLAGS="${CROSS_CFLAGS}"
      CROSS_AR="${CROSS_AR}"
      CROSS_CC="${CROSS_CC}"
      CROSS_MKLIB="${RECIPE_DIR}/building/cross-ocamlmklib.sh"
      CROSS_MKEXE="${CROSS_MKEXE}"
      CROSS_MKDLL="${CROSS_MKDLL}"
      LD="${CROSS_LD}"
      LDFLAGS="${CROSS_LDFLAGS}"
      LIBDIR="${OCAML_CROSS_LIBDIR}"
      NM="${CROSS_NM}"
      RANLIB="${CROSS_RANLIB}"
      STRIP="${CROSS_STRIP}"
      ZSTD_LIBS="-L${BUILD_PREFIX}/lib -lzstd"
      
      SAK_AR="${NATIVE_AR}"
      SAK_CC="${NATIVE_CC}"
      SAK_CFLAGS="${NATIVE_CFLAGS}"
      SAK_LDFLAGS="${NATIVE_LDFLAGS}"

      # NATIVE tools for building BUILD-platform binaries (profiling.cmx, ocamlopt.opt)
      NATIVE_AS="${NATIVE_AS}"
      NATIVE_ASM="${NATIVE_ASM}"  # Includes "-c" for macOS clang
      NATIVE_CC="${NATIVE_CC}"

      # Native compiler stdlib location (for copying fresh .cmi files)
      NATIVE_STDLIB="${NATIVE_STDLIB}"
    )

    run_logged "crossopt" "${MAKE[@]}" crossopt "${CROSSOPT_ARGS[@]}" -j"${CPU_COUNT}" || { cat "${LOG_DIR}"/crossopt.log; exit 1; }
  )

  # ========================================================================
  # Install cross-compiler
  # ========================================================================

  echo "  [6/6] Installing cross-compiler via 'make installcross'..."

  (
    # Use same environment as crossopt
    export CONDA_OCAML_AS="${CROSS_ASM}"
    export CONDA_OCAML_CC="${CROSS_CC}"
    export CONDA_OCAML_AR="${CROSS_AR}"
    export CONDA_OCAML_RANLIB="${CROSS_RANLIB}"
    export CONDA_OCAML_MKDLL="${CROSS_MKDLL}"
    # CONDA_OCAML_MKEXE intentionally NOT set - use native linker

    PATH="${OCAML_PREFIX}/bin:${PATH}"
    hash -r

    INSTALL_ARGS=(
      PREFIX="${OCAML_CROSS_PREFIX}"
      ARCH="${CROSS_ARCH}"
      AR="${CROSS_AR}"
      AS="${CROSS_AS}"
      ASPP="${CROSS_CC} -c"
      CC="${CROSS_CC}"
      CFLAGS="${CROSS_CFLAGS}"
      CROSS_AR="${CROSS_AR}"
      CROSS_CC="${CROSS_CC}"
      CROSS_MKEXE="${CROSS_MKEXE}"
      CROSS_MKDLL="${CROSS_MKDLL}"
      LD="${CROSS_LD}"
      LDFLAGS="${CROSS_LDFLAGS}"
      NM="${CROSS_NM}"
      RANLIB="${CROSS_RANLIB}"
      STRIP="${CROSS_STRIP}"
    )

    # Clean LIBDIR before install to ensure fresh installation
    # This prevents mixing of files from crossopt build with make install
    echo "    Cleaning LIBDIR before install..."
    rm -rf "${OCAML_CROSS_LIBDIR}"

    run_logged "installcross" "${MAKE[@]}" installcross "${INSTALL_ARGS[@]}"
  )

  # Verify rpath for macOS cross-compiler binaries
  # OCaml embeds @rpath/libzstd.1.dylib - rpath should be set via BYTECCLIBS during build
  # Cross-compiler binaries are in ${PREFIX}/lib/ocaml-cross-compilers/${target}/bin/
  # libzstd is in ${PREFIX}/lib/, so relative path is ../../../../lib
  if [[ "${target_platform}" == "osx"* ]]; then
    echo "  Verifying rpath for macOS cross-compiler binaries..."
    for binary in "${OCAML_CROSS_PREFIX}"/bin/*.opt; do
      if [[ -f "${binary}" ]]; then
        # Check if libzstd is linked via @rpath
        if otool -L "${binary}" 2>/dev/null | grep -q "@rpath/libzstd"; then
          # Check if rpath already exists (either @executable_path or @loader_path)
          if otool -l "${binary}" 2>/dev/null | grep -A2 "LC_RPATH" | grep -qE "@(executable_path|loader_path)"; then
            RPATH=$(otool -l "${binary}" 2>/dev/null | grep -A2 "LC_RPATH" | grep "path" | head -1 | awk '{print $2}')
            echo "    $(basename ${binary}): rpath OK (${RPATH})"
          else
            # No rpath set - add one
            echo "    $(basename ${binary}): adding @loader_path/../../../../lib rpath"
            if install_name_tool -add_rpath @loader_path/../../../../lib "${binary}" 2>&1; then
              codesign -f -s - "${binary}" 2>/dev/null || true
            else
              echo "    WARNING: install_name_tool failed for $(basename ${binary})"
            fi
          fi
        fi
      fi
    done
  fi

  # Post-install fixes for cross-compiler package

  # ld.conf - point to native OCaml's stublibs (same arch as cross-compiler binary)
  # Cross-compiler binary runs on BUILD machine, needs BUILD-arch stublibs
  cat > "${OCAML_CROSS_LIBDIR}/ld.conf" << EOF
${OCAML_PREFIX}/lib/ocaml/stublibs
${OCAML_PREFIX}/lib/ocaml
EOF

  # Remove unnecessary binaries to reduce package size
  # Cross-compiler only needs: ocamlopt, ocamlc, ocamldep, ocamllex, ocamlyacc, ocamlmklib
  echo "  Cleaning up unnecessary binaries..."
  (
    cd "${OCAML_CROSS_PREFIX}/bin"

    # Remove bytecode versions (keep only .opt)
    rm -f ocamlc.byte ocamldep.byte ocamllex.byte ocamlobjinfo.byte ocamlopt.byte

    # Remove toplevel and REPL (not needed for cross-compilation)
    rm -f ocaml

    # Remove bytecode interpreters (cross-compiler produces native code)
    rm -f ocamlrun ocamlrund ocamlruni

    # Remove profiling tools
    rm -f ocamlcp ocamloptp ocamlprof

    # Remove other unnecessary tools
    rm -f ocamlcmt ocamlmktop

    # Optionally remove ocamlobjinfo (only for debugging)
    # rm -f ocamlobjinfo ocamlobjinfo.opt
  )

  # Remove man pages (not needed in cross-compiler package)
  rm -rf "${OCAML_CROSS_PREFIX}/man" 2>/dev/null || true

  # Patch Makefile.config for cross-compilation
  # The installed Makefile.config has BUILD machine settings, we need TARGET settings
  # Also clean up build-time paths that would cause test failures and runtime issues
  echo "  Patching Makefile.config for target ${target}..."
  makefile_config="${OCAML_CROSS_LIBDIR}/Makefile.config"
  if [[ -f "${makefile_config}" ]]; then
    # Architecture
    sed -i "s|^ARCH=.*|ARCH=${CROSS_ARCH}|" "${makefile_config}"

    # TOOLPREF - CRITICAL: Must be TARGET triplet, not BUILD triplet!
    # opam uses this to find the correct cross-toolchain
    sed -i "s|^TOOLPREF=.*|TOOLPREF=${target}-|" "${makefile_config}"

    # Model (for PowerPC)
    if [[ -n "${CROSS_MODEL}" ]]; then
      sed -i "s|^MODEL=.*|MODEL=${CROSS_MODEL}|" "${makefile_config}"
    fi

    # Toolchain - use wrapper scripts that expand CONDA_OCAML_* at runtime
    sed -i "s|^CC=.*|CC=conda-ocaml-cc|" "${makefile_config}"
    sed -i "s|^AS=.*|AS=conda-ocaml-as|" "${makefile_config}"
    sed -i "s|^ASM=.*|ASM=conda-ocaml-as|" "${makefile_config}"
    sed -i "s|^ASPP=.*|ASPP=conda-ocaml-cc -c|" "${makefile_config}"
    sed -i "s|^AR=.*|AR=conda-ocaml-ar|" "${makefile_config}"
    sed -i "s|^RANLIB=.*|RANLIB=conda-ocaml-ranlib|" "${makefile_config}"

    # CPP - strip build-time path, keep binary name and flags (-E -P)
    # Pattern: CPP=/long/path/to/clang -E -P -> CPP=clang -E -P
    # The ( .*)? is optional to handle CPP without flags
    sed -Ei 's#^(CPP)=/.*/([^/ ]+)( .*)?$#\1=\2\3#' "${makefile_config}"

    # Linker commands - use cross-tools via wrappers
    sed -i "s|^NATIVE_PACK_LINKER=.*|NATIVE_PACK_LINKER=conda-ocaml-ld -r -o|" "${makefile_config}"
    sed -i "s|^MKEXE=.*|MKEXE=conda-ocaml-mkexe|" "${makefile_config}"
    sed -i "s|^MKDLL=.*|MKDLL=conda-ocaml-mkdll|" "${makefile_config}"
    sed -i "s|^MKMAINDLL=.*|MKMAINDLL=conda-ocaml-mkdll|" "${makefile_config}"

    # Library paths - remove hardcoded BUILD paths, use runtime paths
    # bytecomp_c_libraries and native_c_libraries should not have -L paths
    # that point to BUILD_PREFIX - those won't exist at runtime
    # Patterns to catch: conda-bld, rattler-build, build_env, _build_env
    sed -i 's|-L[^ ]*conda-bld[^ ]* ||g' "${makefile_config}"
    sed -i 's|-L[^ ]*rattler-build[^ ]* ||g' "${makefile_config}"
    sed -i 's|-L[^ ]*build_env[^ ]* ||g' "${makefile_config}"
    sed -i 's|-L[^ ]*_build_env[^ ]* ||g' "${makefile_config}"

    # Ensure zstd is linked correctly (will be found via standard paths at runtime)
    # Remove any remaining absolute -L paths before -lzstd
    sed -i 's|-L/[^ ]*/lib -lzstd|-lzstd|g' "${makefile_config}"
    # Also catch -L without trailing -lzstd
    sed -i 's|-L/[^ ]*/lib ||g' "${makefile_config}"

    # Standard library path - use actual ${PREFIX} which conda will relocate
    # The OCAML_CROSS_LIBDIR variable contains build-time work directory path
    # We need to use the FINAL installed path: ${PREFIX}/lib/ocaml-cross-compilers/${target}/lib/ocaml
    FINAL_CROSS_LIBDIR="${PREFIX}/lib/ocaml-cross-compilers/${target}/lib/ocaml"
    FINAL_CROSS_PREFIX="${PREFIX}/lib/ocaml-cross-compilers/${target}"
    sed -i "s|^prefix=.*|prefix=${FINAL_CROSS_PREFIX}|" "${makefile_config}"
    sed -i "s|^LIBDIR=.*|LIBDIR=${FINAL_CROSS_LIBDIR}|" "${makefile_config}"
    sed -i "s|^STUBLIBDIR=.*|STUBLIBDIR=${FINAL_CROSS_LIBDIR}/stublibs|" "${makefile_config}"

    # CRITICAL: Remove or sanitize CONFIGURE_ARGS - it contains build-time paths
    # This is purely informational but fails tests and confuses users
    # Replace the entire line with a sanitized version
    sed -i '/^CONFIGURE_ARGS=/d' "${makefile_config}"
    echo "CONFIGURE_ARGS=# Removed - contained build-time paths" >> "${makefile_config}"

    # Clean any remaining build-time paths in other fields
    # Pattern: /home/*/build_artifacts/*, /home/*/feedstock_root/*
    # Replace with ${PREFIX} which conda will relocate
    sed -i "s|/home/[^/]*/feedstock_root/[^ ]*|${PREFIX}|g" "${makefile_config}"
    sed -i "s|/home/[^/]*/build_artifacts/[^ ]*|${PREFIX}|g" "${makefile_config}"

    # Remove -Wl,-rpath paths that point to build directories
    sed -i 's|-Wl,-rpath,[^ ]*rattler-build[^ ]* ||g' "${makefile_config}"
    sed -i 's|-Wl,-rpath-link,[^ ]*rattler-build[^ ]* ||g' "${makefile_config}"

    # Clean LDFLAGS - remove build-time paths from LDFLAGS and LDFLAGS?= lines
    # These patterns catch conda-bld, rattler-build, build_env paths
    sed -i 's|-L[^ ]*miniforge[^ ]* ||g' "${makefile_config}"
    sed -i 's|-L[^ ]*miniconda[^ ]* ||g' "${makefile_config}"

    echo "    Patched ARCH=${CROSS_ARCH}"
    [[ -n "${CROSS_MODEL}" ]] && echo "    Patched MODEL=${CROSS_MODEL}"
    echo "    Patched toolchain to use conda-ocaml-* wrappers"
    echo "    Cleaned build-time paths from prefix/LIBDIR/STUBLIBDIR"
    echo "    Removed CONFIGURE_ARGS (contained build-time paths)"
  else
    echo "    WARNING: Makefile.config not found at ${makefile_config}"
  fi

  # Remove unnecessary library files to reduce package size
  echo "  Cleaning up unnecessary library files..."
  (
    cd "${OCAML_CROSS_LIBDIR}"

    # Remove source files (not needed for compilation)
    find . -name "*.ml" -type f -delete 2>/dev/null || true
    find . -name "*.mli" -type f -delete 2>/dev/null || true

    # Remove typed trees (only for IDE tooling, not compilation)
    find . -name "*.cmt" -type f -delete 2>/dev/null || true
    find . -name "*.cmti" -type f -delete 2>/dev/null || true

    # Remove legacy annotation files
    find . -name "*.annot" -type f -delete 2>/dev/null || true

    # Note: Keep .cma/.cmo - dune bootstrap may need bytecode libraries
    # Note: Keep .cmx/.cmxa/.a/.cmi/.o - required for native compilation
  )

  echo "  Installed via make installcross to: ${OCAML_CROSS_PREFIX}"

  # ========================================================================
  # Generate wrapper scripts
  # ========================================================================

  for tool in ocamlopt ocamlc ocamldep ocamlobjinfo ocamllex ocamlyacc ocamlmklib; do
    generate_cross_wrapper "${tool}" "${OCAML_INSTALL_PREFIX}" "${target}" "${OCAML_CROSS_PREFIX}"
    (cd "${OCAML_INSTALL_PREFIX}"/bin && ln -s "${target}-${tool}.opt" "${target}-${tool}")
  done

  echo "  Installed: ${OCAML_INSTALL_PREFIX}/bin/${target}-ocamlopt"
  echo "  Libs:      ${OCAML_CROSS_LIBDIR}/"

  # ========================================================================
  # Basic smoke test
  # ========================================================================

  echo "  Basic smoke test..."
  CROSS_OCAMLOPT="${OCAML_INSTALL_PREFIX}/bin/${target}-ocamlopt"

  if "${CROSS_OCAMLOPT}" -version | grep -q "${PKG_VERSION}"; then
    echo "    ✓ Version check passed"
  else
    echo "    ✗ ERROR: Version mismatch"
    exit 1
  fi

  ${RECIPE_DIR}/testing/test-cross-compiler-consistency.sh "${OCAML_INSTALL_PREFIX}/bin/${target}-ocamlopt"
  
  echo "  Done: ${target} (comprehensive tests run in post-install)"
done

echo ""
echo "============================================================"
echo "All cross-compilers built successfully"
echo "============================================================"
