# ============================================================================
# NATIVE OCAML BUILD SCRIPT
# Builds native OCaml compiler for the current target platform
#
# Variables:
#   OCAML_INSTALL_PREFIX - Where native OCaml will be installed (destination)
#
# Toolchain Variables (NATIVE_*):
#   NATIVE_CC      - C compiler for native code
#   NATIVE_AS      - Assembler for native code
#   NATIVE_AR      - Archive tool
#   NATIVE_RANLIB  - Archive index tool
#   NATIVE_ASM     - Assembler with preprocessing (CC -c)
#
# CONDA_OCAML_* Variables (embedded in binaries for runtime use):
#   CONDA_OCAML_CC      - Runtime C compiler
#   CONDA_OCAML_AS      - Runtime assembler
#   CONDA_OCAML_AR      - Runtime archive tool
#   CONDA_OCAML_RANLIB  - Runtime ranlib
#   CONDA_OCAML_MKEXE   - Runtime executable linker command
#   CONDA_OCAML_MKDLL   - Runtime shared library linker command
# ============================================================================

# Source common functions
source "${RECIPE_DIR}/building/common-functions.sh"

# ============================================================================
# Validate Environment
# ============================================================================

: "${OCAML_INSTALL_PREFIX:=${PREFIX}}"

# Compiler activation should set CONDA_TOOLCHAIN_BUILD
if [[ -z "${CONDA_TOOLCHAIN_BUILD:-}" ]]; then
  echo "ERROR: CONDA_TOOLCHAIN_BUILD not set (compiler activation failed?)"
  exit 1
fi

# ============================================================================
# Native Toolchain Setup (NATIVE_*)
# ============================================================================

echo ""
echo "============================================================"
echo "Native OCaml build configuration"
echo "============================================================"
echo "  Platform:      ${target_platform}"
echo "  Install:       ${OCAML_INSTALL_PREFIX}"

# Native toolchain - simplified basenames (hardcoded in binaries)
# These use CONDA_TOOLCHAIN_BUILD which is set by compiler activation
setup_toolchain "NATIVE" "${CONDA_TOOLCHAIN_BUILD}"
setup_cflags_ldflags "NATIVE" "${build_platform:-${target_platform}}" "${target_platform}"

# Platform-specific overrides
if [[ "${target_platform}" == "osx"* ]]; then
  # macOS: Set library paths for zstd at compile-time and runtime
  # Cross-compilation: BUILD_PREFIX has x86_64 libs for native compiler
  # Native build: PREFIX has x86_64 libs (same arch)
  if [[ "${CONDA_BUILD_CROSS_COMPILATION:-0}" == "1" ]]; then
    export DYLD_LIBRARY_PATH="${BUILD_PREFIX}/lib:${DYLD_LIBRARY_PATH:-}"
    export LIBRARY_PATH="${BUILD_PREFIX}/lib:${LIBRARY_PATH:-}"
  else
    export DYLD_LIBRARY_PATH="${PREFIX}/lib:${DYLD_LIBRARY_PATH:-}"
    export LIBRARY_PATH="${PREFIX}/lib:${LIBRARY_PATH:-}"
  fi
elif [[ "${target_platform}" != "linux"* ]]; then
  [[ ${OCAML_INSTALL_PREFIX} != *"Library"* ]] && OCAML_INSTALL_PREFIX="${OCAML_INSTALL_PREFIX}"/Library
  echo "  Install:       ${OCAML_INSTALL_PREFIX}  <- Non-unix ..."

  NATIVE_WINDRES=$(find_tool "${CONDA_TOOLCHAIN_BUILD}-windres" true)
  [[ ! -f "${PREFIX}/Library/bin/windres.exe" ]] && cp "${NATIVE_WINDRES}" "${PREFIX}/Library/bin/windres.exe"

  # Set UTF-8 codepage
  export PYTHONUTF8=1
  # Needed to find zstd
  export NATIVE_LDFLAGS="-L${_PREFIX_}/Library/lib ${NATIVE_LDFLAGS:-}"
fi

echo "  NATIVE_AR:      ${NATIVE_AR}"
echo "  NATIVE_AS:      ${NATIVE_AS}"
echo "  NATIVE_ASM:     ${NATIVE_ASM}"
echo "  NATIVE_CC:      ${NATIVE_CC}"
echo "  NATIVE_CFLAGS:  ${NATIVE_CFLAGS}"
echo "  NATIVE_LD:      ${NATIVE_LD}"
echo "  NATIVE_LDFLAGS: ${NATIVE_LDFLAGS}"
echo "  NATIVE_RANLIB:  ${NATIVE_RANLIB}"

# ============================================================================
# CONDA_OCAML_* Variables (Runtime Configuration)
# ============================================================================

# These are embedded in binaries and expanded at runtime
# Users can override via environment variables
export CONDA_OCAML_AR=$(basename "${NATIVE_AR}")
export CONDA_OCAML_CC=$(basename "${NATIVE_CC}")
export CONDA_OCAML_LD=$(basename "${NATIVE_LD}")
export CONDA_OCAML_RANLIB=$(basename "${NATIVE_RANLIB}")
# Special case, already a basename
export CONDA_OCAML_AS="${NATIVE_ASM}"
export CONDA_OCAML_MKEXE="${NATIVE_MKEXE}"
export CONDA_OCAML_MKDLL="${NATIVE_MKDLL}"
# non-unix-specific: windres for resource compilation
export CONDA_OCAML_WINDRES="${NATIVE_WINDRES:-windres}"

# ============================================================================
# Export variables for downstream scripts
# ============================================================================
cat > "${SRC_DIR}/_native_compiler_env.sh" << EOF
# Generated by build-native.sh - do not edit
export NATIVE_AR="${NATIVE_AR}"
export NATIVE_AS="${NATIVE_AS}"
export NATIVE_ASM="${NATIVE_ASM}"
export NATIVE_CC="${NATIVE_CC}"
export NATIVE_CFLAGS="${NATIVE_CFLAGS}"
export NATIVE_LD="${NATIVE_LD}"
export NATIVE_LDFLAGS="${NATIVE_LDFLAGS}"
export NATIVE_RANLIB="${NATIVE_RANLIB}"
export NATIVE_INSTALL_PREFIX="${OCAML_INSTALL_PREFIX}"

# CONDA_OCAML_* for runtime
export CONDA_OCAML_AR="${CONDA_OCAML_AR}"
export CONDA_OCAML_AS="${CONDA_OCAML_AS}"
export CONDA_OCAML_CC="${CONDA_OCAML_CC}"
export CONDA_OCAML_LD="${CONDA_OCAML_LD}"
export CONDA_OCAML_RANLIB="${CONDA_OCAML_RANLIB}"
export CONDA_OCAML_MKEXE="${CONDA_OCAML_MKEXE:-}"
export CONDA_OCAML_MKDLL="${CONDA_OCAML_MKDLL:-}"
EOF

# ============================================================================
# Configure Arguments
# ============================================================================

#  --enable-native-toplevel
CONFIG_ARGS+=(
  -prefix "${OCAML_INSTALL_PREFIX}"
  --mandir="${OCAML_INSTALL_PREFIX}"/share/man
)

# Enable ocamltest if running tests
if [[ "${SKIP_MAKE_TESTS:-0}" == "0" ]]; then
  CONFIG_ARGS+=(--enable-ocamltest)
else
  CONFIG_ARGS+=(--disable-ocamltest)
fi

# Add toolchain to configure args
CONFIG_ARGS+=(
  AR="${NATIVE_AR}"
  AS="${NATIVE_AS}"
  CC="${NATIVE_CC}"
  CFLAGS="${NATIVE_CFLAGS}"
  LD="${NATIVE_LD}"
  LDFLAGS="${NATIVE_LDFLAGS}"
  RANLIB="${NATIVE_RANLIB}"
  host_alias="${build_alias:-${host_alias:-${CONDA_TOOLCHAIN_BUILD}}}"
)

if is_unix; then
  CONFIG_ARGS+=(
    --enable-frame-pointers
    --with-target-bindir="${PREFIX}"/bin
  )
else
  CONFIG_ARGS+=(
    --with-flexdll
    --with-gnu-ld
    --with-target-bindir="${PREFIX}"/Library/bin
    windows_UNICODE_MODE=compatible
    WINDRES="${NATIVE_WINDRES}"
  )
fi

# ============================================================================
# Install conda-ocaml-* wrapper scripts BEFORE build (needed during compilation)
# ============================================================================

if is_unix; then
  echo "  Installing conda-ocaml-* wrapper scripts to BUILD_PREFIX..."
  for wrapper in conda-ocaml-cc conda-ocaml-as conda-ocaml-ar conda-ocaml-ld conda-ocaml-ranlib conda-ocaml-mkexe conda-ocaml-mkdll; do
    install -m 755 "${RECIPE_DIR}/scripts/${wrapper}" "${BUILD_PREFIX}/bin/${wrapper}"
  done
  # Debug: verify wrappers installed and environment set
  echo "  Wrapper scripts installed:"
  ls -la "${BUILD_PREFIX}/bin/conda-ocaml-"* 2>/dev/null || echo "    (none found!)"
  echo "  CONDA_OCAML_* environment:"
  echo "    CONDA_OCAML_AS=${CONDA_OCAML_AS:-<unset>}"
  echo "    CONDA_OCAML_CC=${CONDA_OCAML_CC:-<unset>}"
  echo "    CONDA_OCAML_AR=${CONDA_OCAML_AR:-<unset>}"
  echo "    CONDA_OCAML_RANLIB=${CONDA_OCAML_RANLIB:-<unset>}"
  echo "    CONDA_OCAML_MKEXE=${CONDA_OCAML_MKEXE:-<unset>}"
  echo "    CONDA_OCAML_MKDLL=${CONDA_OCAML_MKDLL:-<unset>}"
  echo "  PATH includes BUILD_PREFIX/bin: $(echo "$PATH" | grep -q "${BUILD_PREFIX}/bin" && echo "yes" || echo "NO!")"
else
  # Non-unix: Build wrapper .exe files BEFORE configuring
  # These need to exist when config.generated.ml references them
  echo "  Building conda-ocaml-* wrapper executables to BUILD_PREFIX..."
  WRAPPER_SRC="${RECIPE_DIR}/building/non-unix-conda-ocaml-wrapper.c"
  WRAPPER_DIR="${BUILD_PREFIX}/Library/bin"
  mkdir -p "${WRAPPER_DIR}"

  declare -A WRAPPERS=(
    ["CC"]="gcc.exe"
    ["AS"]="as.exe"
    ["AR"]="ar.exe"
    ["LD"]="ld.exe"
    ["RANLIB"]="ranlib.exe"
    ["WINDRES"]="windres.exe"
  )

  for tool_name in "${!WRAPPERS[@]}"; do
    default_tool="${WRAPPERS[$tool_name]}"
    wrapper_name="conda-ocaml-${tool_name,,}.exe"  # lowercase
    echo "    Building ${wrapper_name}..."
    "${NATIVE_CC}" -O2 -o "${WRAPPER_DIR}/${wrapper_name}" "${WRAPPER_SRC}" \
      -DTOOL_NAME="${tool_name}" \
      -DDEFAULT_TOOL="\"${default_tool}\""
  done
  echo "  Wrapper executables built:"
  ls -la "${WRAPPER_DIR}"/conda-ocaml-*.exe 2>/dev/null || echo "    (none found!)"
fi

# ============================================================================
# Configure
# ============================================================================

echo ""
echo "  [1/4] Configuring native compiler"
run_logged "configure" "${CONFIGURE[@]}" "${CONFIG_ARGS[@]}" -prefix="${OCAML_INSTALL_PREFIX}"

# ============================================================================
# Patch config.generated.ml and Makefil.config
# ============================================================================

echo "  [2/4] Patching config for ocaml-* wrapper scripts"

config_file="utils/config.generated.ml"

# Debug: Check native_compiler exists before patching
echo "    config.generated.ml native_compiler: $(grep 'native_compiler' "$config_file" | head -1 || echo '(not found)')"

# NOTE: Do NOT remove -L paths here - they're needed for the build.
# The -L path removal for bytecomp_c_libraries happens AFTER world.opt build
# but BEFORE install, to avoid non-relocatable paths in installed binaries.

if is_unix; then
  # Unix: Use conda-ocaml-* wrapper scripts that expand CONDA_OCAML_* environment variables
  # This allows tools like Dune to invoke the compiler via Unix.create_process
  # (which doesn't expand shell variables) while still honoring runtime overrides
  sed -i 's/^let asm = .*/let asm = {|conda-ocaml-as|}/' "$config_file"
  sed -i 's/^let ar = .*/let ar = {|conda-ocaml-ar|}/' "$config_file"
  sed -i 's/^let c_compiler = .*/let c_compiler = {|conda-ocaml-cc|}/' "$config_file"
  sed -i 's/^let ranlib = .*/let ranlib = {|conda-ocaml-ranlib|}/' "$config_file"
  sed -i 's/^let mkexe = .*/let mkexe = {|conda-ocaml-mkexe|}/' "$config_file"
  sed -i 's/^let mkdll = .*/let mkdll = {|conda-ocaml-mkdll|}/' "$config_file"
  sed -i 's/^let mkmaindll = .*/let mkmaindll = {|conda-ocaml-mkdll|}/' "$config_file"
else
  # non-unix: Use conda-ocaml-*.exe wrapper executables
  # These read CONDA_OCAML_* environment variables at runtime.
  # Unlike Unix shell scripts, non-unix needs actual .exe wrappers because:
  # - CreateProcess doesn't expand %VAR% (only cmd.exe does)
  # - .bat files don't work as direct executables from CreateProcess
  sed -i 's/^let asm = .*/let asm = {|conda-ocaml-as.exe|}/' "$config_file"
  sed -i 's/^let c_compiler = .*/let c_compiler = {|conda-ocaml-cc.exe|}/' "$config_file"
  sed -i 's/^let ar = .*/let ar = {|conda-ocaml-ar.exe|}/' "$config_file"
  sed -i 's/^let ranlib = .*/let ranlib = {|conda-ocaml-ranlib.exe|}/' "$config_file"
  # NOTE: Do NOT override mkexe/mkdll/mkmaindll on non-unix!
  # These use flexlink which has complex behavior that shouldn't be wrapped.
  # Let OCaml+flexlink handle linking directly.
fi

# Clean up Makefile.config - remove embedded paths that cause issues
config_file="Makefile.config"
sed -i  's#-fdebug-prefix-map=[^ ]*##g' "${config_file}"
sed -i  's#-link\s+-L[^ ]*##g' "${config_file}"                             # Remove flexlink's "-link -L..." patterns
sed -i  's#-L[^ ]*##g' "${config_file}"                                     # Remove standalone -L paths
# These would be found in BUILD_PREFIX and fail relocation
# Remove prepended binaries path (could be BUILD_PREFIX non-relocatable)
# Simple commands: CC, AS, ASM, ASPP, STRIP (line ends with binary name)
sed -Ei 's#^(CC|AS|ASM|ASPP|STRIP)=/.*/([^/]+)$#\1=\2#' "${config_file}"
# CPP has flags after binary (e.g., "/path/to/clang -E -P" -> "clang -E -P")
# The ( .*)? is optional to handle CPP without flags
sed -Ei 's#^(CPP)=/.*/([^/ ]+)( .*)?$#\1=\2\3#' "${config_file}"

if [[ "${target_platform}" == "osx"* ]]; then
  # For cross-compilation, use BUILD_PREFIX (has x86_64 libs for native compiler)
  # For native build (osx-64), use PREFIX (same arch, normal behavior)
  if [[ "${CONDA_BUILD_CROSS_COMPILATION:-0}" == "1" ]]; then
    _LIB_PREFIX="${BUILD_PREFIX}"
  else
    _LIB_PREFIX="${PREFIX}"
  fi

  # OC_LDFLAGS may not exist - append or create
  if grep -q '^OC_LDFLAGS=' "${config_file}"; then
    sed -i "s|^OC_LDFLAGS=\(.*\)|OC_LDFLAGS=\1 -Wl,-L${_LIB_PREFIX}/lib -Wl,-headerpad_max_install_names|" "${config_file}"
  else
    echo "OC_LDFLAGS=-Wl,-L${_LIB_PREFIX}/lib -Wl,-headerpad_max_install_names" >> "${config_file}"
  fi

  # These should exist - append to them
  sed -i "s|^NATIVECCLINKOPTS=\(.*\)|NATIVECCLINKOPTS=\1 -Wl,-L${_LIB_PREFIX}/lib -Wl,-headerpad_max_install_names|" "${config_file}"
  sed -i "s|^NATIVECCLIBS=\(.*\)|NATIVECCLIBS=\1 -L${_LIB_PREFIX}/lib -lzstd|" "${config_file}"
  # Fix BYTECCLIBS for -output-complete-exe (links libcamlrun.a which contains zstd.o)
  # Use @loader_path for relocatable rpath (survives conda relocation)
  # Note: Don't use -L${PREFIX}/lib here - conda-ocaml-mkexe wrapper adds it at runtime
  sed -i "s|^BYTECCLIBS=\(.*\)|BYTECCLIBS=\1 -Wl,-rpath,@loader_path/../lib -lzstd|" "${config_file}"
elif [[ "${target_platform}" != "linux"* ]]; then
  # non-unix: Fix flexlink toolchain detection
  sed -i 's/^TOOLCHAIN.*/TOOLCHAIN=mingw64/' "$config_file"
  sed -i 's/^FLEXDLL_CHAIN.*/FLEXDLL_CHAIN=mingw64/' "$config_file"

  # Fix $(addprefix -link ,$(OC_LDFLAGS)) generating garbage when empty
  # Use $(if $(strip ...)) to guard against empty/whitespace-only values
  # NOTE: All $() must be escaped or bash interprets them as command substitution
  sed -i 's/\$(addprefix -link ,\$(OC_LDFLAGS))/\$(if \$(strip \$(OC_LDFLAGS)),\$(addprefix -link ,\$(OC_LDFLAGS)),)/g' "$config_file"
  sed -i 's/\$(addprefix -link ,\$(OC_DLL_LDFLAGS))/\$(if \$(strip \$(OC_DLL_LDFLAGS)),\$(addprefix -link ,\$(OC_DLL_LDFLAGS)),)/g' "$config_file"

  # Remove trailing "-link " garbage from MKEXE/MKDLL lines
  # Configure generates "... $(addprefix...) -link " but when OC_LDFLAGS is empty,
  # this trailing "-link" causes "flexlink ... -link -o output" which passes -o to linker!
  sed -i 's/^\(MK[A-Z]*=.*\)[[:space:]]*-link[[:space:]]*$/\1/' "$config_file"
fi

# ============================================================================
# Build
# ============================================================================

echo "  [3/4] Compiling native compiler"
run_logged "world" "${MAKE[@]}" world.opt -j"${CPU_COUNT}"

# ============================================================================
# Tests (Optional)
# ============================================================================

if [[ "${SKIP_MAKE_TESTS:-0}" == "0" ]]; then
  echo "  - Running tests"
  run_logged "ocamltest" "${MAKE[@]}"  ocamltest -j "${CPU_COUNT}"
  run_logged "test" "${MAKE[@]}"  tests -j "${CPU_COUNT}"
fi

# ============================================================================
# Install
# ============================================================================

echo "  [4/4] Installing native compiler"

# Install (INSTALLING=1 and VPATH= help prevent stale file issues if Makefile.cross is included)
run_logged "install" "${MAKE[@]}" install INSTALLING=1 VPATH=

# Clean hardcoded -L paths from installed Makefile.config
# During build we added -L${BUILD_PREFIX}/lib or -L${PREFIX}/lib to find zstd
# But these absolute paths won't exist at runtime - clean them out
echo "  - Cleaning hardcoded -L paths from installed Makefile.config..."
installed_config="${OCAML_INSTALL_PREFIX}/lib/ocaml/Makefile.config"
if [[ -f "${installed_config}" ]]; then
  # Remove -L paths containing build directories (conda-bld, rattler-build, build_env)
  sed -i 's|-L[^ ]*conda-bld[^ ]* ||g' "${installed_config}"
  sed -i 's|-L[^ ]*rattler-build[^ ]* ||g' "${installed_config}"
  sed -i 's|-L[^ ]*build_env[^ ]* ||g' "${installed_config}"
  sed -i 's|-L[^ ]*_build_env[^ ]* ||g' "${installed_config}"
  # Remove any remaining absolute -L paths (will find libs via standard paths at runtime)
  sed -i 's|-L/[^ ]*/lib ||g' "${installed_config}"
  # Clean -Wl,-L paths too
  sed -i 's|-Wl,-L[^ ]* ||g' "${installed_config}"
fi

# Verify rpath for macOS binaries
# OCaml embeds @rpath/libzstd.1.dylib - rpath should be set via BYTECCLIBS during build
# This verifies the rpath is present and adds it only if missing
if [[ "${target_platform}" == "osx"* ]]; then
  echo "  - Verifying rpath for macOS binaries..."
  for binary in "${OCAML_INSTALL_PREFIX}"/bin/*.opt; do
    if [[ -f "${binary}" ]]; then
      # Check if libzstd is linked via @rpath
      if otool -L "${binary}" 2>/dev/null | grep -q "@rpath/libzstd"; then
        # Check if rpath already exists (either @executable_path or @loader_path)
        if otool -l "${binary}" 2>/dev/null | grep -A2 "LC_RPATH" | grep -qE "@(executable_path|loader_path)"; then
          RPATH=$(otool -l "${binary}" 2>/dev/null | grep -A2 "LC_RPATH" | grep "path" | head -1 | awk '{print $2}')
          echo "    $(basename ${binary}): rpath OK (${RPATH})"
        else
          # No rpath set - add one
          echo "    $(basename ${binary}): adding @loader_path/../lib rpath"
          if install_name_tool -add_rpath @loader_path/../lib "${binary}" 2>&1; then
            codesign -f -s - "${binary}" 2>/dev/null || true
          else
            echo "    WARNING: install_name_tool failed for $(basename ${binary})"
          fi
        fi
      fi
    fi
  done
fi

# Install conda-ocaml-* wrappers (expand CONDA_OCAML_* env vars for tools like Dune)
if is_unix; then
  echo "  - Installing conda-ocaml-* wrapper scripts..."
  for wrapper in conda-ocaml-cc conda-ocaml-as conda-ocaml-ar conda-ocaml-ld conda-ocaml-ranlib conda-ocaml-mkexe conda-ocaml-mkdll; do
    install -m 755 "${RECIPE_DIR}/scripts/${wrapper}" "${OCAML_INSTALL_PREFIX}/bin/${wrapper}"
  done
else
  # non-unix: Build and install wrapper .exe files
  # These are small C programs that read CONDA_OCAML_* env vars at runtime
  echo "  - Building conda-ocaml-* wrapper executables..."
  WRAPPER_SRC="${RECIPE_DIR}/building/non-unix-conda-ocaml-wrapper.c"
  WRAPPER_DIR="${OCAML_INSTALL_PREFIX}/bin"
  mkdir -p "${WRAPPER_DIR}"

  # Build each wrapper with appropriate defaults
  declare -A WRAPPERS=(
    ["CC"]="gcc.exe"
    ["AS"]="as.exe"
    ["AR"]="ar.exe"
    ["LD"]="ld.exe"
    ["RANLIB"]="ranlib.exe"
    ["WINDRES"]="windres.exe"
  )

  for tool_name in "${!WRAPPERS[@]}"; do
    default_tool="${WRAPPERS[$tool_name]}"
    wrapper_name="conda-ocaml-${tool_name,,}.exe"  # lowercase
    echo "    Building ${wrapper_name}..."
    "${NATIVE_CC}" -O2 -o "${WRAPPER_DIR}/${wrapper_name}" "${WRAPPER_SRC}" \
      -DTOOL_NAME="${tool_name}" \
      -DDEFAULT_TOOL="\"${default_tool}\""
  done
fi

# Clean up for potential cross-compiler builds
run_logged "distclean" "${MAKE[@]}"  distclean

echo ""
echo "============================================================"
echo "Native OCaml installed successfully"
echo "============================================================"
echo "  Location: ${OCAML_INSTALL_PREFIX}"
echo "  Version:  $(${OCAML_INSTALL_PREFIX}/bin/ocamlopt -version 2>/dev/null || echo 'N/A')"
