# ============================================================================
# CROSS-COMPILERS BUILD SCRIPT
# Builds cross-compilers for aarch64/ppc64le (on linux-64) or arm64 (on osx-64)
#
# Variables:
#   OCAML_PREFIX         - Where native OCaml is installed (source for native tools)
#   OCAML_INSTALL_PREFIX - Where cross-compilers will be installed (destination)
# ============================================================================

# Source common functions
source "${RECIPE_DIR}/building/common-functions.sh"

if [[ "${target_platform}" != "linux"* ]] && [[ "${target_platform}" != "osx"* ]]; then
  echo "No cross-compiler recipe for ${target_platform} ... yet"
  return 0
fi

# ============================================================================
# Configuration
# ============================================================================

# OCAML_PREFIX = where native OCaml is installed (source for native tools)
# OCAML_INSTALL_PREFIX = where cross-compilers will be installed (destination)
: "${OCAML_PREFIX:=${PREFIX}}"
: "${OCAML_INSTALL_PREFIX:=${PREFIX}}"

# Define cross targets based on build platform
declare -a CROSS_TARGETS
case "${target_platform}" in
  linux-64)
    CROSS_TARGETS=("aarch64-conda-linux-gnu" "powerpc64le-conda-linux-gnu")
    ;;
  linux-aarch64)
    CROSS_TARGETS=("aarch64-conda-linux-gnu")
    ;;
  linux-ppc64le)
    CROSS_TARGETS=("powerpc64le-conda-linux-gnu")
    ;;
  osx-*)
    CROSS_TARGETS=("arm64-apple-darwin20.0.0")
    ;;
esac

# ============================================================================
# Build loop
# ============================================================================

echo ""
echo "============================================================"
echo "Cross-compiler build configuration"
echo "============================================================"
echo "  Native OCaml (source):    ${OCAML_PREFIX}"
echo "  Cross install (dest):     ${OCAML_INSTALL_PREFIX}"
echo "  Native ocamlopt:          ${OCAML_PREFIX}/bin/ocamlopt"

for target in "${CROSS_TARGETS[@]}"; do
  echo ""
  echo "  ------------------------------------------------------------"
  echo "  Building cross-compiler for ${target}"
  echo "  ------------------------------------------------------------"

  # Get target properties using common functions
  CROSS_ARCH=$(get_target_arch "${target}")
  CROSS_PLATFORM=$(get_target_platform "${target}")

  # Handle PowerPC model override
  CROSS_MODEL=""
  [[ "${target}" == "powerpc64le-"* ]] && CROSS_MODEL="ppc64le"

  # Setup cross-toolchain (sets CROSS_CC, CROSS_AS, CROSS_AR, etc.)
  setup_toolchain "CROSS" "${target}"
  setup_cflags_ldflags "CROSS" "${build_platform}" "${CROSS_PLATFORM}"

  # Export CONDA_OCAML_<TARGET_ID>_* variables
  TARGET_ID=$(get_target_id "${target}")

  echo "  Target:        ${target}"
  echo "  Target ID:     ${TARGET_ID}"
  echo "  Arch:          ${CROSS_ARCH}"
  echo "  Platform:      ${CROSS_PLATFORM}"
  echo "  CROSS_AR:      ${CROSS_AR}"
  echo "  CROSS_AS:      ${CROSS_AS}"
  echo "  CROSS_CC:      ${CROSS_CC}"
  echo "  CROSS_CFLAGS:  ${CROSS_CFLAGS}"
  echo "  CROSS_LD:      ${CROSS_LD}"
  echo "  CROSS_LDFLAGS: ${CROSS_LDFLAGS}"
  echo "  CROSS_RANLIB:  ${CROSS_RANLIB}"

  cat > "${SRC_DIR}/_xcross_compiler_${target_platform}_env.sh" << EOF
# Generated by build-cross-compiler.sh - do not edit
export "CROSS_AR=${CROSS_AR}"
export "CROSS_AS=${CROSS_AS}"
export "CROSS_CC=${CROSS_CC}"
export "CROSS_CFLAGS=${CROSS_CFLAGS}"
export "CROSS_LD=${CROSS_LD}"
export "CROSS_LDFLAGS=${CROSS_LDFLAGS}"
export "CROSS_RANLIB=${CROSS_RANLIB}"
export "CROSS_MKDLL=${CROSS_MKDLL}"
export "CROSS_MKEXE=${CROSS_MKEXE}"

# CONDA_OCAML_* for runtime
export "CONDA_OCAML_${TARGET_ID}_AR=${CONDA_OCAML_AR}"
export "CONDA_OCAML_${TARGET_ID}_AS=${CONDA_OCAML_AS}"
export "CONDA_OCAML_${TARGET_ID}_CC=${CONDA_OCAML_CC}"
export "CONDA_OCAML_${TARGET_ID}_RANLIB=${CONDA_OCAML_RANLIB}"
export "CONDA_OCAML_${TARGET_ID}_MKDLL=${CROSS_MKDLL}"
export "CONDA_OCAML_${TARGET_ID}_MKEXE=${CROSS_MKEXE}"
EOF

  # Installation prefix for this cross-compiler
  OCAML_CROSS_PREFIX="${OCAML_INSTALL_PREFIX}/lib/ocaml-cross-compilers/${target}"
  OCAML_CROSS_LIBDIR="${OCAML_CROSS_PREFIX}/lib/ocaml"
  mkdir -p "${OCAML_CROSS_PREFIX}/bin" "${OCAML_CROSS_LIBDIR}"

  # ========================================================================
  # Clean and configure
  # ========================================================================

  echo "  [1/5] Cleaning previous build..."
  run_logged "pre-cross-distclean" "${MAKE[@]}" distclean > /dev/null 2>&1 || true

  echo "  [2/5] Configuring for ${target}..."
  # PKG_CONFIG=false forces simple "-lzstd" instead of "-L/long/path -lzstd"
  # Do NOT pass CC here - configure needs BUILD compiler
  # ac_cv_func_getentropy=no: conda-forge uses glibc 2.17 sysroot which lacks getentropy
  run_logged "cross-configure" ${CONFIGURE[@]} \
    -prefix="${OCAML_CROSS_PREFIX}" \
    --host="${build_alias}" \
    --target="${target}" \
    --enable-frame-pointers \
    "${CONFIG_ARGS[@]}" \
    AR="${CROSS_AR}" \
    CC="${NATIVE_CC}" \
    NM="${CROSS_NM}" \
    RANLIB="${CROSS_RANLIB}" \
    STRIP="${CROSS_STRIP}" \
    ac_cv_func_getentropy=no \
    ${CROSS_MODEL:+MODEL=${CROSS_MODEL}}
    # AS="${NATIVE_AS}" \
    # LD="${NATIVE_LD}" \

  # ========================================================================
  # Patch config.generated.ml
  # ========================================================================

  echo "  [3/5] Patching config.generated.ml..."
  config_file="utils/config.generated.ml"

  # Use ocaml-* wrapper scripts instead of $CONDA_OCAML_* variable references
  # Wrappers expand env vars at runtime, compatible with Unix.create_process
  sed -i \
    -e 's#^let asm = .*#let asm = {|ocaml-as|}#' \
    -e 's#^let ar = .*#let ar = {|ocaml-ar|}#' \
    -e 's#^let c_compiler = .*#let c_compiler = {|ocaml-cc|}#' \
    -e 's#^let ranlib = .*#let ranlib = {|ocaml-ranlib|}#' \
    -e 's#^let mkexe = .*#let mkexe = {|ocaml-mkexe|}#' \
    -e 's#^let mkdll = .*#let mkdll = {|ocaml-mkdll|}#' \
    -e 's#^let mkmaindll = .*#let mkmaindll = {|ocaml-mkdll|}#' \
    "$config_file"
  sed -i "s#^let standard_library_default = .*#let standard_library_default = {|${OCAML_CROSS_LIBDIR}|}#" "$config_file"
  [[ -n "${CROSS_MODEL}" ]] && sed -i "s#^let model = .*#let model = {|${CROSS_MODEL}|}#" "$config_file"

  # Apply "${MAKE[@]}"file.cross patches
  cp "${RECIPE_DIR}/building/Makefile.cross" .
  patch -N -p0 < "${RECIPE_DIR}/building/tmp_Makefile.patch" > /dev/null 2>&1 || true

  # ========================================================================
  # Build cross-compiler
  # ========================================================================

  echo "  [4/5] Building cross-compiler (crossopt)..."

  (
    # Set CONDA_OCAML_* for cross-compilation during build
    # NOTE: CC/AS/AR/RANLIB are CROSS tools (for compiling ARM64/PPC64 stdlib)
    # BUT: MKEXE must stay NATIVE (for linking the x86_64 cross-compiler binary)
    # CONDA_OCAML_MKEXE inherits native value from _native_env.sh - DO NOT override!
    CONDA_OCAML_AS="${CROSS_AS}"
    CONDA_OCAML_CC="${CROSS_CC}"
    CONDA_OCAML_AR="${CROSS_AR}"
    CONDA_OCAML_RANLIB="${CROSS_RANLIB}"
    CONDA_OCAML_MKDLL="${CROSS_MKDLL}"
    # CONDA_OCAML_MKEXE intentionally NOT set - use native linker for cross-compiler binary

    # Ensure cross-tools are findable in PATH
    PATH="${OCAML_PREFIX}/bin:${PATH}"
    hash -r

    # Build arguments
    CROSSOPT_ARGS=(
      ARCH="${CROSS_ARCH}"
      AR="${CROSS_AR}"
      AS="${CROSS_AS}"
      ASPP="${CROSS_CC} -c"
      CAMLOPT=ocamlopt
      CC="${CROSS_CC}"
      CFLAGS="${CROSS_CFLAGS}"
      CROSS_AR="${CROSS_AR}"
      CROSS_CC="${CROSS_CC}"
      CROSS_MKLIB="${RECIPE_DIR}/building/cross-ocamlmklib.sh"
      LD="${CROSS_LD}"
      LDFLAGS="${CROSS_LDFLAGS}"
      LIBDIR="${OCAML_CROSS_LIBDIR}"
      NM="${CROSS_NM}"
      RANLIB="${CROSS_RANLIB}"
      STRIP="${CROSS_STRIP}"
      ZSTD_LIBS="-L${BUILD_PREFIX}/lib -lzstd"
      
      SAK_AR="${NATIVE_AR}"
      SAK_CC="${NATIVE_CC}"
      SAK_CFLAGS="${NATIVE_CFLAGS}"
      SAK_LDFLAGS="${NATIVE_LDFLAGS}"
    )

    run_logged "crossopt" "${MAKE[@]}" crossopt "${CROSSOPT_ARGS[@]}" -j"${CPU_COUNT}"
  )

  # ========================================================================
  # Install cross-compiler
  # ========================================================================

  echo "  [5/5] Installing cross-compiler artifacts..."

  # Binaries
  cp ocamlopt.opt "${OCAML_CROSS_PREFIX}/bin/"
  cp ocamlc.opt "${OCAML_CROSS_PREFIX}/bin/"
  cp tools/ocamldep.opt "${OCAML_CROSS_PREFIX}/bin/"
  cp tools/ocamlobjinfo.opt "${OCAML_CROSS_PREFIX}/bin/"

  # Stdlib (bytecode + native + metadata)
  cp stdlib/*.{cma,cmxa,a,cmi,cmo,cmx,o} "${OCAML_CROSS_LIBDIR}/" 2>/dev/null
  cp stdlib/*runtime*info "${OCAML_CROSS_LIBDIR}/" 2>/dev/null

  # Compiler libs
  cp compilerlibs/*.{cma,cmxa,a} "${OCAML_CROSS_LIBDIR}/" 2>/dev/null

  # Runtime
  cp runtime/*.{a,o} "${OCAML_CROSS_LIBDIR}/" 2>/dev/null

  # Otherlibs
  for lib in otherlibs/*/; do
    cp "${lib}"*.{cma,cmxa,a,cmi,cmo,cmx,o} "${OCAML_CROSS_LIBDIR}/" 2>/dev/null
  done

  # Stublibs
  mkdir -p "${OCAML_CROSS_LIBDIR}/stublibs"
  cp otherlibs/*/dll*.so "${OCAML_CROSS_LIBDIR}/stublibs/" 2>/dev/null

  # ld.conf - point to native OCaml's stublibs (same arch as cross-compiler binary)
  # Cross-compiler binary runs on BUILD machine, needs BUILD-arch stublibs
  cat > "${OCAML_CROSS_LIBDIR}/ld.conf" << EOF
${OCAML_PREFIX}/lib/ocaml/stublibs
${OCAML_PREFIX}/lib/ocaml
EOF

  # ========================================================================
  # Generate wrapper scripts
  # ========================================================================

  for tool in ocamlopt ocamlc ocamldep ocamlobjinfo; do
    generate_cross_wrapper "${tool}" "${OCAML_INSTALL_PREFIX}" "${target}" "${OCAML_CROSS_PREFIX}"
  done

  echo "  Installed: ${OCAML_INSTALL_PREFIX}/bin/${target}-ocamlopt"
  echo "  Libs:      ${OCAML_CROSS_LIBDIR}/"

  # ========================================================================
  # Test cross-compiler
  # ========================================================================

  echo "  Testing cross-compiler..."
  "${OCAML_INSTALL_PREFIX}/bin/${target}-ocamlopt" -version | grep -q "${PKG_VERSION}"

  cat > /tmp/test_xcross_compiler.ml << 'TESTEOF'
let () = print_endline "Hello from cross-compiled OCaml"
TESTEOF

  if "${OCAML_INSTALL_PREFIX}/bin/${target}-ocamlopt" -o /tmp/test_xcross_compiler /tmp/test_xcross_compiler.ml 2>/dev/null; then
    _file_output=$(file /tmp/test_xcross_compiler)
    case "${CROSS_ARCH}" in
      arm64)
        echo "$_file_output" | grep -qiE "aarch64|arm64" && echo "  ✓ Produces ${CROSS_ARCH} binaries" || {
          echo "  ✗ ERROR: expected ${CROSS_ARCH}, got: $_file_output"
          exit 1
        }
        ;;
      power)
        echo "$_file_output" | grep -qi "powerpc\|ppc64" && echo "  ✓ Produces ${CROSS_ARCH} binaries" || {
          echo "  ✗ ERROR: expected ${CROSS_ARCH}, got: $_file_output"
          exit 1
        }
        ;;
    esac
    rm -f /tmp/test_xcross_compiler /tmp/test_xcross_compiler.ml /tmp/test_xcross_compiler.{o,cmx,cmi}
  else
    echo "  ✗ ERROR: cross-compilation failed"
    "${OCAML_INSTALL_PREFIX}/bin/${target}-ocamlopt" -verbose -o /tmp/test_xcross_compiler /tmp/test_xcross_compiler.ml || true
    exit 1
  fi

  echo "  Done: ${target}"
done

echo ""
echo "============================================================"
echo "All cross-compilers built successfully"
echo "============================================================"
