# ============================================================================
# NATIVE OCAML BUILD SCRIPT
# Builds native OCaml compiler for the current target platform
#
# Variables:
#   OCAML_INSTALL_PREFIX - Where native OCaml will be installed (destination)
#
# Toolchain Variables (NATIVE_*):
#   NATIVE_CC      - C compiler for native code
#   NATIVE_AS      - Assembler for native code
#   NATIVE_AR      - Archive tool
#   NATIVE_RANLIB  - Archive index tool
#   NATIVE_ASM     - Assembler with preprocessing (CC -c)
#
# CONDA_OCAML_* Variables (embedded in binaries for runtime use):
#   CONDA_OCAML_CC      - Runtime C compiler
#   CONDA_OCAML_AS      - Runtime assembler
#   CONDA_OCAML_AR      - Runtime archive tool
#   CONDA_OCAML_RANLIB  - Runtime ranlib
#   CONDA_OCAML_MKEXE   - Runtime executable linker command
#   CONDA_OCAML_MKDLL   - Runtime shared library linker command
# ============================================================================

# Source common functions
source "${RECIPE_DIR}/building/common-functions.sh"

# ============================================================================
# Validate Environment
# ============================================================================

: "${OCAML_INSTALL_PREFIX:=${PREFIX}}"

# Compiler activation should set CONDA_TOOLCHAIN_BUILD
if [[ -z "${CONDA_TOOLCHAIN_BUILD:-}" ]]; then
  echo "ERROR: CONDA_TOOLCHAIN_BUILD not set (compiler activation failed?)"
  exit 1
fi

# ============================================================================
# Native Toolchain Setup (NATIVE_*)
# ============================================================================

echo ""
echo "============================================================"
echo "Native OCaml build configuration"
echo "============================================================"
echo "  Platform:      ${target_platform}"
echo "  Install:       ${OCAML_INSTALL_PREFIX}"

# Native toolchain - simplified basenames (hardcoded in binaries)
# These use CONDA_TOOLCHAIN_BUILD which is set by compiler activation
setup_toolchain "NATIVE" "${CONDA_TOOLCHAIN_BUILD}"
setup_cflags_ldflags "NATIVE" "${build_platform:-${target_platform}}" "${target_platform}"

# Platform-specific overrides
if [[ "${target_platform}" == "osx"* ]]; then
  # For native compiler (Stage 1), use BUILD_PREFIX only
  # The native compiler runs on BUILD machine, needs BUILD-arch libraries
  # PREFIX contains target-arch libraries which are incompatible during cross-compilation
  export DYLD_LIBRARY_PATH="${BUILD_PREFIX}/lib:${DYLD_LIBRARY_PATH:-}"
  export LIBRARY_PATH="${BUILD_PREFIX}/lib:${LIBRARY_PATH:-}"
elif [[ "${target_platform}" != "linux"* ]]; then
  [[ ${OCAML_INSTALL_PREFIX} != *"Library"* ]] && OCAML_INSTALL_PREFIX="${OCAML_INSTALL_PREFIX}"/Library
  echo "  Install:       ${OCAML_INSTALL_PREFIX}  <- Non-unix ..."

  NATIVE_WINDRES=$(find_tool "${CONDA_TOOLCHAIN_BUILD}-windres" true)
  [[ ! -f "${PREFIX}/Library/bin/windres.exe" ]] && cp "${NATIVE_WINDRES}" "${PREFIX}/Library/bin/windres.exe"

  # Set UTF-8 codepage
  export PYTHONUTF8=1
  # Needed to find zstd
  export NATIVE_LDFLAGS="-L${_PREFIX_}/Library/lib ${NATIVE_LDFLAGS:-}"
fi

echo "  NATIVE_AR:      ${NATIVE_AR}"
echo "  NATIVE_AS:      ${NATIVE_AS}"
echo "  NATIVE_ASM:     ${NATIVE_ASM}"
echo "  NATIVE_CC:      ${NATIVE_CC}"
echo "  NATIVE_CFLAGS:  ${NATIVE_CFLAGS}"
echo "  NATIVE_LD:      ${NATIVE_LD}"
echo "  NATIVE_LDFLAGS: ${NATIVE_LDFLAGS}"
echo "  NATIVE_RANLIB:  ${NATIVE_RANLIB}"

# ============================================================================
# CONDA_OCAML_* Variables (Runtime Configuration)
# ============================================================================

# These are embedded in binaries and expanded at runtime
# Users can override via environment variables
export CONDA_OCAML_AR=$(basename "${NATIVE_AR}")
export CONDA_OCAML_CC=$(basename "${NATIVE_CC}")
export CONDA_OCAML_RANLIB=$(basename "${NATIVE_RANLIB}")
# Special case, already a basename
export CONDA_OCAML_AS="${NATIVE_ASM}"
export CONDA_OCAML_MKEXE="${NATIVE_MKEXE}"
export CONDA_OCAML_MKDLL="${NATIVE_MKDLL}"

# ============================================================================
# Export variables for downstream scripts
# ============================================================================
cat > "${SRC_DIR}/_native_compiler_env.sh" << EOF
# Generated by build-native.sh - do not edit
export NATIVE_AR="${NATIVE_AR}"
export NATIVE_AS="${NATIVE_AS}"
export NATIVE_ASM="${NATIVE_ASM}"
export NATIVE_CC="${NATIVE_CC}"
export NATIVE_CFLAGS="${NATIVE_CFLAGS}"
export NATIVE_LD="${NATIVE_LD}"
export NATIVE_LDFLAGS="${NATIVE_LDFLAGS}"
export NATIVE_RANLIB="${NATIVE_RANLIB}"
export NATIVE_INSTALL_PREFIX="${OCAML_INSTALL_PREFIX}"

# CONDA_OCAML_* for runtime
export CONDA_OCAML_AR="${CONDA_OCAML_AR}"
export CONDA_OCAML_AS="${CONDA_OCAML_AS}"
export CONDA_OCAML_CC="${CONDA_OCAML_CC}"
export CONDA_OCAML_RANLIB="${CONDA_OCAML_RANLIB}"
export CONDA_OCAML_MKEXE="${CONDA_OCAML_MKEXE:-}"
export CONDA_OCAML_MKDLL="${CONDA_OCAML_MKDLL:-}"
EOF

# ============================================================================
# Configure Arguments
# ============================================================================

#  --enable-native-toplevel
CONFIG_ARGS+=(
  -prefix "${OCAML_INSTALL_PREFIX}"
  --mandir="${OCAML_INSTALL_PREFIX}"/share/man
)

# Enable ocamltest if running tests
if [[ "${SKIP_MAKE_TESTS:-0}" == "0" ]]; then
  CONFIG_ARGS+=(--enable-ocamltest)
else
  CONFIG_ARGS+=(--disable-ocamltest)
fi

# Add toolchain to configure args
CONFIG_ARGS+=(
  AR="${NATIVE_AR}"
  AS="${NATIVE_AS}"
  CC="${NATIVE_CC}"
  CFLAGS="${NATIVE_CFLAGS}"
  LD="${NATIVE_LD}"
  LDFLAGS="${NATIVE_LDFLAGS}"
  RANLIB="${NATIVE_RANLIB}"
  
  host_alias="${build_alias:-${host_alias:-${CONDA_TOOLCHAIN_BUILD}}}"
)

if is_unix; then
  CONFIG_ARGS+=(
    --with-target-bindir="${PREFIX}"/bin
    --enable-frame-pointers
  )
else
  CONFIG_ARGS+=(
    --with-flexdll
    --with-gnu-ld
    --with-target-bindir="${PREFIX}"/Library/bin
    WINDOWS_UNICODE_MODE=compatible
    WINDRES="${NATIVE_WINDRES}"
  )
fi

# ============================================================================
# Install ocaml-* wrapper scripts BEFORE build (needed during compilation)
# ============================================================================

if is_unix; then
  echo "  Installing ocaml-* wrapper scripts to BUILD_PREFIX..."
  for wrapper in ocaml-cc ocaml-as ocaml-ar ocaml-ranlib ocaml-mkexe ocaml-mkdll; do
    install -m 755 "${RECIPE_DIR}/scripts/${wrapper}" "${BUILD_PREFIX}/bin/${wrapper}"
  done
  # Debug: verify wrappers installed and environment set
  echo "  Wrapper scripts installed:"
  ls -la "${BUILD_PREFIX}/bin/ocaml-"* 2>/dev/null || echo "    (none found!)"
  echo "  CONDA_OCAML_* environment:"
  echo "    CONDA_OCAML_AS=${CONDA_OCAML_AS:-<unset>}"
  echo "    CONDA_OCAML_CC=${CONDA_OCAML_CC:-<unset>}"
  echo "    CONDA_OCAML_AR=${CONDA_OCAML_AR:-<unset>}"
  echo "    CONDA_OCAML_RANLIB=${CONDA_OCAML_RANLIB:-<unset>}"
  echo "    CONDA_OCAML_MKEXE=${CONDA_OCAML_MKEXE:-<unset>}"
  echo "    CONDA_OCAML_MKDLL=${CONDA_OCAML_MKDLL:-<unset>}"
  echo "  PATH includes BUILD_PREFIX/bin: $(echo "$PATH" | grep -q "${BUILD_PREFIX}/bin" && echo "yes" || echo "NO!")"
fi

# ============================================================================
# Configure
# ============================================================================

echo ""
echo "  [1/4] Configuring native compiler"
run_logged "configure" "${CONFIGURE[@]}" "${CONFIG_ARGS[@]}" -prefix="${OCAML_INSTALL_PREFIX}"

# ============================================================================
# Patch config.generated.ml and Makefil.config
# ============================================================================

echo "  [2/4] Patching config for ocaml-* wrapper scripts"

config_file="utils/config.generated.ml"

# Debug: Check native_compiler exists before patching
echo "    config.generated.ml native_compiler: $(grep 'native_compiler' "$config_file" | head -1 || echo '(not found)')"

# Remove -L paths from bytecomp_c_libraries (embedded in ocamlc binary)
# Use more specific pattern to avoid affecting other content
sed -i 's#\(bytecomp_c_libraries.*\)-L[^ ]*#\1#g' "$config_file"

if is_unix; then
  # Unix: Use ocaml-* wrapper scripts that expand CONDA_OCAML_* environment variables
  # This allows tools like Dune to invoke the compiler via Unix.create_process
  # (which doesn't expand shell variables) while still honoring runtime overrides
  sed -i 's/^let asm = .*/let asm = {|ocaml-as|}/' "$config_file"
  sed -i 's/^let ar = .*/let ar = {|ocaml-ar|}/' "$config_file"
  sed -i 's/^let c_compiler = .*/let c_compiler = {|ocaml-cc|}/' "$config_file"
  sed -i 's/^let ranlib = .*/let ranlib = {|ocaml-ranlib|}/' "$config_file"
  sed -i 's/^let mkexe = .*/let mkexe = {|ocaml-mkexe|}/' "$config_file"
  sed -i 's/^let mkdll = .*/let mkdll = {|ocaml-mkdll|}/' "$config_file"
  sed -i 's/^let mkmaindll = .*/let mkmaindll = {|ocaml-mkdll|}/' "$config_file"
else
  # Windows: Embed actual tool basenames directly
  # %CONDA_OCAML_*% doesn't work because CreateProcess doesn't expand %VAR%
  # (only cmd.exe does). Use the tool basenames we already computed.
  sed -i "s/^let asm = .*/let asm = {|${CONDA_OCAML_AS}|}/" "$config_file"
  sed -i "s/^let c_compiler = .*/let c_compiler = {|${CONDA_OCAML_CC}|}/" "$config_file"
  sed -i "s/^let ar = .*/let ar = {|${CONDA_OCAML_AR}|}/" "$config_file"
  sed -i "s/^let ranlib = .*/let ranlib = {|${CONDA_OCAML_RANLIB}|}/" "$config_file"
fi

# Clean up Makefile.config - remove embedded paths that cause issues
config_file="Makefile.config"
sed -i  's#-fdebug-prefix-map=[^ ]*##g' "${config_file}"
sed -i  's#-link\s+-L[^ ]*##g' "${config_file}"                             # Remove flexlink's "-link -L..." patterns
sed -i  's#-L[^ ]*##g' "${config_file}"                                     # Remove standalone -L paths
# These would be found in BUILD_PREFIX and fail relocation
sed -Ei 's#^(CC|CPP|ASM|ASPP|STRIP)=/.*/([^/]+)$#\1=\2#' "${config_file}"   # Remove prepended binaries path (could be BUILD_PREFIX non-relocatable)

if [[ "${target_platform}" == "osx"* ]]; then
  # macOS: Add -headerpad_max_install_names and zstd to linker flags
  # NOTE: Must use double quotes so ${PREFIX} and ${BUILD_PREFIX} are expanded by bash
  echo "  macOS Makefile.config before fix:"
  echo "    OC_LDFLAGS:        $(grep -E '^OC_LDFLAGS=' "${config_file}" || echo '(not found)')"
  echo "    NATIVECCLINKOPTS:  $(grep -E '^NATIVECCLINKOPTS=' "${config_file}" || echo '(not found)')"
  echo "    NATIVECCLIBS:      $(grep -E '^NATIVECCLIBS=' "${config_file}" || echo '(not found)')"

  # For the native compiler (Stage 1), we ONLY want BUILD_PREFIX libraries
  # because the native compiler runs on the BUILD machine (x86_64 for cross-compilation)
  # PREFIX contains target-arch libraries (ARM64) which are incompatible
  #
  # OC_LDFLAGS may not exist - append or create
  if grep -q '^OC_LDFLAGS=' "${config_file}"; then
    sed -i "s|^OC_LDFLAGS=\(.*\)|OC_LDFLAGS=\1 -Wl,-L${BUILD_PREFIX}/lib -Wl,-headerpad_max_install_names|" "${config_file}"
  else
    echo "OC_LDFLAGS=-Wl,-L${BUILD_PREFIX}/lib -Wl,-headerpad_max_install_names" >> "${config_file}"
  fi

  # These should exist - append to them (use BUILD_PREFIX only for native compiler)
  sed -i "s|^NATIVECCLINKOPTS=\(.*\)|NATIVECCLINKOPTS=\1 -Wl,-L${BUILD_PREFIX}/lib -Wl,-headerpad_max_install_names|" "${config_file}"
  sed -i "s|^NATIVECCLIBS=\(.*\)|NATIVECCLIBS=\1 -L${BUILD_PREFIX}/lib -lzstd|" "${config_file}"

  echo "  macOS Makefile.config after fix:"
  echo "    OC_LDFLAGS:        $(grep -E '^OC_LDFLAGS=' "${config_file}" || echo '(not found)')"
  echo "    NATIVECCLINKOPTS:  $(grep -E '^NATIVECCLINKOPTS=' "${config_file}" || echo '(not found)')"
  echo "    NATIVECCLIBS:      $(grep -E '^NATIVECCLIBS=' "${config_file}" || echo '(not found)')"
elif [[ "${target_platform}" != "linux"* ]]; then
  # Windows: Fix flexlink toolchain detection
  sed -i 's/^TOOLCHAIN.*/TOOLCHAIN=mingw64/' "$config_file"
  sed -i 's/^FLEXDLL_CHAIN.*/FLEXDLL_CHAIN=mingw64/' "$config_file"

  # Debug: Show relevant Windows config before fix
  echo "  Windows Makefile.config before fix:"
  echo "    TOOLCHAIN:     $(grep -E '^TOOLCHAIN=' "$config_file" || echo '(not found)')"
  echo "    FLEXDLL_CHAIN: $(grep -E '^FLEXDLL_CHAIN=' "$config_file" || echo '(not found)')"
  echo "    MKEXE:         $(grep -E '^MKEXE=' "$config_file" || echo '(not found)')"
  echo "    MKDLL:         $(grep -E '^MKDLL=' "$config_file" || echo '(not found)')"
  echo "    OC_LDFLAGS:    $(grep -E '^OC_LDFLAGS=' "$config_file" || echo '(not found)')"
  echo "    OUTPUTEXE:     $(grep -E '^OUTPUTEXE=' "$config_file" || echo '(not found)')"

  # Fix $(addprefix -link ,$(OC_LDFLAGS)) generating garbage when empty
  # Use $(if $(strip ...)) to guard against empty/whitespace-only values
  # NOTE: All $() must be escaped or bash interprets them as command substitution
  sed -i 's/\$(addprefix -link ,\$(OC_LDFLAGS))/\$(if \$(strip \$(OC_LDFLAGS)),\$(addprefix -link ,\$(OC_LDFLAGS)),)/g' "$config_file"
  sed -i 's/\$(addprefix -link ,\$(OC_DLL_LDFLAGS))/\$(if \$(strip \$(OC_DLL_LDFLAGS)),\$(addprefix -link ,\$(OC_DLL_LDFLAGS)),)/g' "$config_file"

  # Remove trailing "-link " garbage from MKEXE/MKDLL lines
  # Configure generates "... $(addprefix...) -link " but when OC_LDFLAGS is empty,
  # this trailing "-link" causes "flexlink ... -link -o output" which passes -o to linker!
  sed -i 's/^\(MK[A-Z]*=.*\)[[:space:]]*-link[[:space:]]*$/\1/' "$config_file"

  # Debug: Show MKEXE after fix
  echo "  Windows Makefile.config after fix:"
  echo "    MKEXE:         $(grep -E '^MKEXE=' "$config_file" || echo '(not found)')"
  echo "    MKDLL:         $(grep -E '^MKDLL=' "$config_file" || echo '(not found)')"
fi

# ============================================================================
# Build
# ============================================================================

echo "  [3/4] Compiling native compiler"
run_logged "world" "${MAKE[@]}" world.opt -j"${CPU_COUNT}"

# ============================================================================
# Tests (Optional)
# ============================================================================

if [[ "${SKIP_MAKE_TESTS:-0}" == "0" ]]; then
  echo "  - Running tests"
  run_logged "ocamltest" "${MAKE[@]}"  ocamltest -j "${CPU_COUNT}"
  run_logged "test" "${MAKE[@]}"  tests -j "${CPU_COUNT}"
fi

# ============================================================================
# Install
# ============================================================================

echo "  [4/4] Installing native compiler"
run_logged "install" "${MAKE[@]}"  install

# Install ocaml-* wrapper scripts (expand CONDA_OCAML_* env vars for tools like Dune)
if is_unix; then
  echo "  - Installing ocaml-* wrapper scripts..."
  for wrapper in ocaml-cc ocaml-as ocaml-ar ocaml-ranlib ocaml-mkexe ocaml-mkdll; do
    install -m 755 "${RECIPE_DIR}/scripts/${wrapper}" "${OCAML_INSTALL_PREFIX}/bin/${wrapper}"
  done
fi

# # Save build config for cross-compiler builds
# cp runtime/build_config.h "${SRC_DIR}"

# Clean up for potential cross-compiler builds
run_logged "distclean" "${MAKE[@]}"  distclean

echo ""
echo "============================================================"
echo "Native OCaml installed successfully"
echo "============================================================"
echo "  Location: ${OCAML_INSTALL_PREFIX}"
echo "  Version:  $(${OCAML_INSTALL_PREFIX}/bin/ocamlopt -version 2>/dev/null || echo 'N/A')"
