--- Makefile
+++ Makefile
@@ -2213,8 +2213,11 @@
 	$<
 
 .INTERMEDIATE: tools/checkstack$(EXE) tools/checkstack.$(O)
+tools/checkstack.$(O): tools/checkstack.c
+	$(V_CC)$(CHECKSTACK_CC) $(OC_CFLAGS) $(CFLAGS) $(OUTPUTOBJ)$@ -c $<
+
 tools/checkstack$(EXE): tools/checkstack.$(O)
-	$(V_MKEXE)$(MKEXE) $(OUTPUTEXE)$@ $<
+	$(V_MKEXE)$(CHECKSTACK_CC) $(OC_LDFLAGS) $(LDFLAGS) $(OUTPUTEXE)$@ $<
 else
 checkstack:
 	@
@@ -2971,6 +2974,11 @@
 ifneq "$(HOST)" "$(TARGET)"
 include Makefile.cross
 endif
+# conda-forge: Also include for BUILD != HOST (cross-compiling native binaries)
+# This will be removed once OCaml 5.4.0 is available natively on conda-forge
+ifneq "$(BUILD)" "$(HOST)"
+include Makefile.cross
+endif
 
 Makefile.config Makefile.build_config: config.status
 config.status:
